import {blank,localDate,validate,validDate,ordered,upsert} from './model.js';
import {quoteFor} from './quotes.js';
const MOODS=[{id:1,c:'#C96A5A',mouth:'M8 16.5 Q12 13.5 16 16.5'},{id:2,c:'#C9963A',mouth:'M8 15.5 Q12 14.5 16 15.5'},{id:3,c:'#9A9283',mouth:'M8 15.5 H16'},{id:4,c:'#7FA88E',mouth:'M8 14.5 Q12 17 16 14.5'},{id:5,c:'#2A5445',mouth:'M7.5 14 Q12 18.5 16.5 14'}];
const face=(M,active)=>`<svg width="28" height="28" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="${active?M.c:'#cfc6b2'}"/><circle cx="8.6" cy="9.6" r="1.3" fill="#FFFDF4"/><circle cx="15.4" cy="9.6" r="1.3" fill="#FFFDF4"/><path d="${M.mouth}" fill="none" stroke="#FFFDF4" stroke-width="1.7" stroke-linecap="round"/></svg>`;
const $=id=>document.getElementById(id),embedded=new URLSearchParams(location.search).get('embedded')==='1'||window.parent!==window,KEY='spyr-notebook:v1';let state=blank(),draft,timer,confirmAction,hostStatus='managed',storageBlocked=false,dirty=false;
const newPage=()=>({id:crypto.randomUUID(),date:localDate(),title:'',body:'',updatedAt:new Date().toISOString()});
let todayPage=newPage();
try{if(!embedded){const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}}catch{storageBlocked=true;$('notice').textContent='Your previous notebook could not be read. It has not been overwritten. Export any new writing before leaving.';}
function pages(){const entries=ordered(state);if(draft&&!entries.some(e=>e.id===draft.id))entries.push(draft);if(!entries.some(e=>e.date===localDate())&&!entries.some(e=>e.id===todayPage.id))entries.push(todayPage);return ordered({entries});}
function status(){ $('status').textContent=embedded?(hostStatus==='error'?'Not saved · retry':hostStatus==='saving'?'Saving…':hostStatus==='saved'?'Saved':''):storageBlocked?'Not saved · export a copy':'';$('retry').hidden=embedded?hostStatus!=='error':!storageBlocked;}
function persist(){if(!embedded&&!storageBlocked){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageBlocked=true;$('notice').textContent='Could not save on this device. Your writing is still here—export a backup.';}}window.dispatchEvent(new CustomEvent('spyr:notebook-change',{detail:structuredClone(state)}));status();}
function commit(){clearTimeout(timer);if(!draft||!dirty)return;if(!draft.title.trim()&&!draft.body.trim()&&draft.mood==null&&!state.entries.some(e=>e.id===draft.id)){status();return;}state=upsert(state,draft);dirty=false;persist();navigation();}
function navigation(){const all=pages(),index=all.findIndex(e=>e.id===draft.id);$('previous').disabled=index<=0;$('next').disabled=index>=all.length-1;$('position').textContent=(index+1)+' / '+all.length;$('remove').disabled=!state.entries.some(e=>e.id===draft.id);}
function drawMood(){const box=$('mood');box.replaceChildren();for(const M of MOODS){const b=document.createElement('button');b.type='button';b.className='face'+(draft.mood===M.id?' on':'');b.setAttribute('aria-pressed',String(draft.mood===M.id));b.setAttribute('aria-label','Mood '+M.id+' of 5');b.innerHTML=face(M,draft.mood==null||draft.mood===M.id);b.onclick=()=>{draft.mood=draft.mood===M.id?null:M.id;draft.updatedAt=new Date().toISOString();dirty=true;drawMood();clearTimeout(timer);timer=setTimeout(commit,150);};box.append(b);}}
function draw(){const date=new Date(draft.date+'T12:00:00');$('calendar').replaceChildren();const q=quoteFor(draft.date);$('quote').replaceChildren();const qt=document.createElement('p'),qb=document.createElement('small');qt.textContent='“'+q.t+'”';qb.textContent='— '+q.by;$('quote').append(qt,qb);drawMood();const n=ordered(state).findIndex(e=>e.id===draft.id);$('entry-no').textContent=n>=0?'PAGE '+String(n+1).padStart(2,'0'):'NEW PAGE';const day=document.createElement('b'),month=document.createElement('span');day.textContent=date.getDate();month.textContent=date.toLocaleDateString(undefined,{month:'long',year:'numeric'});$('calendar').append(day,month);$('date-label').textContent=date.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric',year:'numeric'});$('title').value=draft.title;$('body').value=draft.body;$('body').scrollTop=0;wordCount();status();navigation();}
function wordCount(){const words=draft.body.trim()?draft.body.trim().split(/\s+/).length:0;$('words').textContent=words+' '+(words===1?'word':'words');}
function turnTo(entry,direction='forward'){commit();const old={...draft};draft={...entry};draw();if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const layer=$('turn');layer.replaceChildren();const title=document.createElement('h2'),body=document.createElement('p');title.textContent=old.title||'Untitled';body.textContent=old.body;layer.append(title,body);layer.className='';void layer.offsetWidth;layer.className=direction;} }
function today(){commit();const existing=ordered(state).filter(e=>e.date===localDate()).at(-1);turnTo(existing||todayPage);$('body').focus();}
function change(delta){const all=pages(),index=all.findIndex(e=>e.id===draft.id),entry=all[index+delta];if(entry)turnTo(entry,delta<0?'backward':'forward');}
for(const id of ['title','body'])$(id).addEventListener('input',()=>{dirty=true;draft.title=$('title').value;draft.body=$('body').value;draft.updatedAt=new Date().toISOString();wordCount();$('status').textContent='Saving…';clearTimeout(timer);timer=setTimeout(commit,350);});
$('previous').onclick=()=>change(-1);$('next').onclick=()=>change(1);$('today').onclick=today;
function renderIndex(){const query=$('search').value.toLowerCase();$('list').replaceChildren();const matches=ordered(state).reverse().filter(e=>(e.date+' '+e.title+' '+e.body).toLowerCase().includes(query));if(!matches.length){$('list').textContent=state.entries.length?'No matching pages.':'No entries yet.';return;}for(const e of matches){const b=document.createElement('button'),date=document.createElement('small'),title=document.createElement('strong'),excerpt=document.createElement('p');date.textContent=e.date;title.textContent=e.title||'Untitled';excerpt.textContent=e.body.slice(0,120)||'';b.append(date,title,excerpt);b.onclick=()=>{$('index').close();turnTo(e);};$('list').append(b);}}
$('browse').onclick=()=>{commit();renderIndex();$('index').showModal();};$('search').oninput=renderIndex;
$('change-date').onclick=()=>{$('date-input').value=draft.date;$('dates').showModal();};$('date-cancel').onclick=()=>$('dates').close();$('date-form').onsubmit=e=>{e.preventDefault();if(!validDate($('date-input').value))return;if(draft.id===todayPage.id&&$('date-input').value!==todayPage.date)todayPage=newPage();dirty=true;draft.date=$('date-input').value;draft.updatedAt=new Date().toISOString();commit();draw();$('dates').close();};
function confirm(title,copy,action){$('confirm-title').textContent=title;$('confirm-copy').textContent=copy;confirmAction=action;$('confirm').showModal();}$('cancel').onclick=()=>$('confirm').close();$('proceed').onclick=()=>{$('confirm').close();confirmAction?.();confirmAction=null;};
$('remove').onclick=()=>confirm('Remove this page?','This deletes the current entry. Export a backup first if you want to keep a copy.',()=>{clearTimeout(timer);dirty=false;state.entries=state.entries.filter(e=>e.id!==draft.id);draft={...(ordered(state).at(-1)||newPage())};persist();draw();});
$('export').onclick=()=>{commit();const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='spyr-notebook.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>10000000)throw Error('Choose a backup smaller than 10 MB.');const incoming=validate(JSON.parse(await f.text()));confirm('Replace this notebook?',incoming.entries.length+' entries will replace your current notebook. Export your current notebook first to keep a copy.',()=>{clearTimeout(timer);dirty=false;state=incoming;draft={...(ordered(state).at(-1)||newPage())};persist();draw();});}catch(error){$('notice').textContent=error.message;}finally{$('file').value='';}};
$('retry').onclick=()=>{if(embedded){window.dispatchEvent(new CustomEvent('spyr:notebook-retry'));return;}try{const existing=localStorage.getItem(KEY);if(existing)validate(JSON.parse(existing));storageBlocked=false;persist();}catch{$('notice').textContent='The stored notebook is still unreadable. Export your current writing before resolving device storage.';}};
window.addEventListener('pagehide',commit);document.addEventListener('visibilitychange',()=>{if(document.hidden)commit();});document.addEventListener('keydown',e=>{if(e.altKey&&(e.key==='ArrowLeft'||e.key==='ArrowRight')&&!document.querySelector('dialog[open]')){e.preventDefault();change(e.key==='ArrowLeft'?-1:1);}});
window.SPYRNotebook={getState(){commit();return structuredClone(state);},loadState(raw){const next=validate(raw);clearTimeout(timer);dirty=false;state=next;draft={...(ordered(state).at(-1)||newPage())};draw();},flush:commit,setSaveStatus(value){hostStatus=value;status();}};
if(embedded){$('export').hidden=true;$('import').hidden=true;$('host-exit').hidden=false;document.body.classList.add('embedded');$('host-exit').onclick=()=>{commit();try{window.parent.postMessage({type:'spyr:notebook-exit'},location.origin);}catch{}};}
draft={...(ordered(state).filter(e=>e.date===localDate()).at(-1)||todayPage)};draw();
