export const QUOTES = [
  { t: "I am grateful for this body that carries me through every single day.", by: "Affirmation" },
  { t: "Today I choose to notice what is going right.", by: "Affirmation" },
  { t: "I am thankful for the breath in my lungs and the strength in my legs.", by: "Affirmation" },
  { t: "Small joys are still joys, and my life is full of them.", by: "Affirmation" },
  { t: "I am grateful for the people who check in on me.", by: "Affirmation" },
  { t: "My morning coffee, warm and unhurried, is a gift.", by: "Affirmation" },
  { t: "I appreciate how far I have come, even when the road felt slow.", by: "Affirmation" },
  { t: "I am thankful for a bed to rest in and a reason to get up.", by: "Affirmation" },
  { t: "Gratitude turns what I have into enough.", by: "Affirmation" },
  { t: "I am grateful for the lessons hidden inside hard days.", by: "Affirmation" },
  { t: "Someone laughed with me recently, and that mattered.", by: "Affirmation" },
  { t: "I am thankful for clean water, warm food, and quiet moments.", by: "Affirmation" },
  { t: "My body healed something this week without being asked.", by: "Affirmation" },
  { t: "I am grateful for second chances, especially the ones I gave myself.", by: "Affirmation" },
  { t: "Today is unrepeatable, and I get to live it.", by: "Affirmation" },
  { t: "I appreciate the friends who feel like home.", by: "Affirmation" },
  { t: "I am thankful for music that understands me.", by: "Affirmation" },
  { t: "The sun rose again today, and so did I.", by: "Affirmation" },
  { t: "I am grateful for the strength I didn't know I had until I needed it.", by: "Affirmation" },
  { t: "I appreciate every meal made with care, including the simple ones.", by: "Affirmation" },
  { t: "I am thankful for the ability to learn, change, and begin again.", by: "Affirmation" },
  { t: "Rest is a gift, and today I accept it.", by: "Affirmation" },
  { t: "I am grateful for laughter that arrives at exactly the right time.", by: "Affirmation" },
  { t: "My past self worked hard for the life I have now. Thank you.", by: "Affirmation" },
  { t: "I am thankful for fresh air and the freedom to walk in it.", by: "Affirmation" },
  { t: "I notice and appreciate the kindness of strangers.", by: "Affirmation" },
  { t: "I am grateful for my five senses and everything they let me experience.", by: "Affirmation" },
  { t: "Today I am thankful for progress, not perfection.", by: "Affirmation" },
  { t: "I appreciate the roof over my head and the safety it gives me.", by: "Affirmation" },
  { t: "I am grateful for the family I was given and the family I chose.", by: "Affirmation" },
  { t: "Every heartbeat is something I never had to earn.", by: "Affirmation" },
  { t: "I am thankful for books, stories, and ideas that expand me.", by: "Affirmation" },
  { t: "I appreciate my own resilience — I have survived every hard day so far.", by: "Affirmation" },
  { t: "I am grateful for the seasons and the reminder that everything changes.", by: "Affirmation" },
  { t: "Someone believed in me once, and it changed things. Thank you.", by: "Affirmation" },
  { t: "I am thankful for slow mornings and soft evenings.", by: "Affirmation" },
  { t: "I appreciate the work my hands can do.", by: "Affirmation" },
  { t: "I am grateful for forgiveness — given, received, and self-directed.", by: "Affirmation" },
  { t: "Today I choose gratitude over comparison.", by: "Affirmation" },
  { t: "I am thankful for the technology that keeps me close to people I love.", by: "Affirmation" },
  { t: "I appreciate nature's patience: trees grow slowly and still become mighty.", by: "Affirmation" },
  { t: "I am grateful for my health, in all the ways it shows up for me.", by: "Affirmation" },
  { t: "A stranger smiled at me once and I still remember it.", by: "Affirmation" },
  { t: "I am thankful for warm showers and clean clothes.", by: "Affirmation" },
  { t: "I appreciate the courage it took to become who I am.", by: "Affirmation" },
  { t: "I am grateful for pets and animals that love without conditions.", by: "Affirmation" },
  { t: "Today I am thankful for the meal in front of me.", by: "Affirmation" },
  { t: "I appreciate quiet — the world's most underrated luxury.", by: "Affirmation" },
  { t: "I am grateful that I get to try again tomorrow.", by: "Affirmation" },
  { t: "My struggles taught me things comfort never could.", by: "Affirmation" },
  { t: "I am thankful for teachers, formal and accidental.", by: "Affirmation" },
  { t: "I appreciate my past for shaping me and my future for waiting for me.", by: "Affirmation" },
  { t: "I am grateful for hands to hold and shoulders to lean on.", by: "Affirmation" },
  { t: "Sunlight through a window is a small miracle I refuse to ignore.", by: "Affirmation" },
  { t: "I am thankful for my sense of humor — it has carried me far.", by: "Affirmation" },
  { t: "I appreciate every person who stayed.", by: "Affirmation" },
  { t: "I am grateful for the chance to be someone's reason to smile today.", by: "Affirmation" },
  { t: "Today I honor the ordinary: it is quietly extraordinary.", by: "Affirmation" },
  { t: "I am thankful for growth I can feel but not always see.", by: "Affirmation" },
  { t: "I appreciate rain, and what it does for everything that grows.", by: "Affirmation" },
  { t: "I am grateful for my mind, curious and still learning.", by: "Affirmation" },
  { t: "I have enough. I am enough. Today, that is plenty.", by: "Affirmation" },
  { t: "I am thankful for the invisible work my body does every second.", by: "Affirmation" },
  { t: "I appreciate honest conversations, even the uncomfortable ones.", by: "Affirmation" },
  { t: "I am grateful for beginnings, endings, and the courage both require.", by: "Affirmation" },
  { t: "Someone cooked for me once with love. I still taste it.", by: "Affirmation" },
  { t: "I am thankful for this exact, imperfect, irreplaceable day.", by: "Affirmation" },
  { t: "I appreciate the streets I know by heart and the places still unknown.", by: "Affirmation" },
  { t: "I am grateful for sleep and the mercy of waking rested.", by: "Affirmation" },
  { t: "Today I am thankful for one small thing I usually overlook.", by: "Affirmation" },
  { t: "I appreciate my own company more than I used to.", by: "Affirmation" },
  { t: "I am grateful for every risk that taught me I could.", by: "Affirmation" },
  { t: "Kindness costs nothing and I received some today.", by: "Affirmation" },
  { t: "I am thankful for the freedom to choose my thoughts.", by: "Affirmation" },
  { t: "I appreciate old photographs and the proof of joy they hold.", by: "Affirmation" },
  { t: "I am grateful for hobbies that ask nothing but my presence.", by: "Affirmation" },
  { t: "My heart has been broken and it still works. Thank you, heart.", by: "Affirmation" },
  { t: "I am thankful for the earth beneath me — steady, generous, alive.", by: "Affirmation" },
  { t: "I appreciate deadlines missed and disasters that never came.", by: "Affirmation" },
  { t: "I am grateful for the doctors, helpers, and healers of the world.", by: "Affirmation" },
  { t: "Today I choose to be thankful before I am asked to be.", by: "Affirmation" },
  { t: "I am thankful for my voice and the things it can say kindly.", by: "Affirmation" },
  { t: "I appreciate every version of me that got me here.", by: "Affirmation" },
  { t: "I am grateful for windows, light, and things that open.", by: "Affirmation" },
  { t: "A good stretch in the morning is gratitude in motion.", by: "Affirmation" },
  { t: "I am thankful for challenges that turned out to be doorways.", by: "Affirmation" },
  { t: "I appreciate the meals shared and the stories told over them.", by: "Affirmation" },
  { t: "I am grateful for silence after a long day.", by: "Affirmation" },
  { t: "Today I am thankful for someone I have never thanked out loud.", by: "Affirmation" },
  { t: "I appreciate my own patience, still under construction.", by: "Affirmation" },
  { t: "I am grateful for the small routines that hold my days together.", by: "Affirmation" },
  { t: "Warm socks. Cold water. Fresh air. Thank you.", by: "Affirmation" },
  { t: "I am thankful for the people who tell me the truth gently.", by: "Affirmation" },
  { t: "I appreciate time — the only gift everyone receives daily.", by: "Affirmation" },
  { t: "I am grateful for what my hands built, my feet walked, my heart held.", by: "Affirmation" },
  { t: "Today, being alive is achievement enough, and I am grateful for it.", by: "Affirmation" },
  { t: "I appreciate the person reading this — me — for showing up again.", by: "Affirmation" },
  { t: "I am thankful that gratitude itself is free, renewable, and mine.", by: "Affirmation" },
  { t: "The best things in my life were never things.", by: "Affirmation" },
  { t: "Reflect upon your present blessings, of which every man has many.", by: "Charles Dickens" },
  { t: "Enjoy the little things, for one day you may look back and realize they were the big things.", by: "Robert Brault" },
  { t: "Wear gratitude like a cloak and it will feed every corner of your life.", by: "Rumi" },
  { t: "Gratitude turns what we have into enough.", by: "Aesop (attributed)" },
  { t: "Give thanks for a little and you will find a lot.", by: "Hausa proverb" },
  { t: "The root of joy is gratefulness.", by: "David Steindl-Rast" },
  { t: "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.", by: "John F. Kennedy" },
  { t: "Feeling gratitude and not expressing it is like wrapping a present and not giving it.", by: "William Arthur Ward" },
  { t: "Gratitude is the fairest blossom which springs from the soul.", by: "Henry Ward Beecher" },
  { t: "He who receives a benefit with gratitude repays the first installment on his debt.", by: "Seneca" },
  { t: "Nothing is more honorable than a grateful heart.", by: "Seneca" },
  { t: "Let us rise up and be thankful — for if we didn't learn a lot today, at least we learned a little.", by: "Buddha (attributed)" },
  { t: "Piglet noticed that even though he had a Very Small Heart, it could hold a rather large amount of Gratitude.", by: "A. A. Milne" },
  { t: "Gratitude is riches. Complaint is poverty.", by: "Doris Day" },
  { t: "When you are grateful, fear disappears and abundance appears.", by: "Old saying" },
  { t: "Gratitude is not only the greatest of virtues, but the parent of all the others.", by: "Cicero" },
  { t: "If the only prayer you ever say in your entire life is thank you, it will be enough.", by: "Meister Eckhart" },
  { t: "It is not joy that makes us grateful; it is gratitude that makes us joyful.", by: "David Steindl-Rast" },
  { t: "When you arise in the morning, think of what a precious privilege it is to be alive.", by: "Marcus Aurelius" },
  { t: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", by: "Epictetus" },
  { t: "Wear gratitude like a cloak and it will feed every corner of your life.", by: "Rumi" },
  { t: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", by: "Melody Beattie" },
  { t: "Enjoy the little things, for one day you may look back and realize they were the big things.", by: "Robert Brault" },
  { t: "Gratitude is the fairest blossom which springs from the soul.", by: "Henry Ward Beecher" },
  { t: "The highest appreciation is not to utter words, but to live by them.", by: "John F. Kennedy" },
];
export const quoteFor=(date,seed=0)=>QUOTES[(([...date].reduce((a,c)=>a*31+c.charCodeAt(0),3)>>>0)+seed)%QUOTES.length];
