import {TrainingScene} from './training-scene.js';
import {makeWorkout} from './program-data.js';
import {movements} from './collection-data.js';
class RouteScene{
 constructor(canvas){this.canvas=canvas;this.time=0;this.paused=true;this.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;}
 async load(w){this.image=new Image();await new Promise((yes,no)=>{this.image.onload=yes;this.image.onerror=no;this.image.src='assets/'+(w.audio?(w.category==='bike'?'category-cycling':'category-running'):w.background)+'.webp';});}
 set(move,kind,paused,progress){this.paused=paused;this.progress=progress;}
 update(dt){if(!this.paused&&this.motion)this.time+=dt;const c=this.canvas,box=c.getBoundingClientRect();c.width=Math.max(1,Math.round(box.width));c.height=Math.max(1,Math.round(box.height));const x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#172b23';x.fillRect(0,0,w,h);if(this.image){const scale=Math.max(w/this.image.width,h/this.image.height)*(1+(this.motion?Math.sin(this.time/20)*.008+.01:0));x.drawImage(this.image,(w-this.image.width*scale)/2,(h-this.image.height*scale)/2,this.image.width*scale,this.image.height*scale);}x.fillStyle='#071b2350';x.fillRect(0,0,w,h);}
}
export class CollectionScene{
 constructor(canvas,onStatus){this.canvas=canvas;this.onStatus=onStatus;this.scenes=new Map();this.active=null;this.wanted=null;}
 async load(w){this.matWorkout=['yoga','pilates'].includes(w.category);const groups=new Map();for(const key of new Set([...w.entries.map(e=>e.key),...(this.matWorkout?['matRest','mountain']:[]),...(w.audio?[w.category==='bike'?'rideEasy':'walk']:[]),...(w.trainer==='01'?['kaiMarch']:[])])){const m=movements[key],group=m.art.kind==='gym'?'gym':m.art.kind==='audio'?'audio':m.art.course;if(!groups.has(group))groups.set(group,[]);groups.get(group).push(m);}this.onStatus('Preparing the room…');let failures=0;
 await Promise.all([...groups].map(async([group,ms])=>{if(group==='audio'){const scene=new RouteScene(this.canvas);try{await scene.load(w);this.scenes.set(group,scene);}catch{failures++;}return;}const scene=new TrainingScene(this.canvas,message=>{if(message?.includes('could not'))failures++;});const course=group==='gym'?{id:w.id,atlas:'gym-collection',trainer:w.trainer,moves:Object.fromEntries(ms.map(m=>[m.art.move,{name:m.name,cue:m.cue}]))}:makeWorkout(group,20);if(ms.some(m=>m.art.move==='carry'))course.moves.carry={...course.moves.carry,hold:true,holdFrame:0};Object.assign(course,{background:w.background,ground:this.matWorkout?.9:.8,backgroundZoom:this.matWorkout?1.2:1,presentation:'cinematic',mobileFloor:.65,centered:w.category==='run'});await scene.load(course);this.scenes.set(group,scene);}));if(failures){this.onStatus('Artwork could not load. Reload before starting.');throw Error('Incomplete artwork');}this.onStatus(null);if(this.wanted)this.set(...this.wanted);}
 set(key,kind,paused,progress,side=''){this.wanted=[key,kind,paused,progress,side];if(this.matWorkout&&kind==='rest'){key=['mountain','lowLunge','tree','warrior','opener'].includes(key)?'mountain':'matRest';side='';}const m=movements[key],scene=this.scenes.get(m.art.kind==='gym'?'gym':m.art.kind==='audio'?'audio':m.art.course);if(!scene)return;this.active=scene;scene.set(m.art.move,kind,paused,progress,side);}
 update(dt){this.active?.update(dt);}
}
