import {farmPlots,growthTime,nearby} from './farm-rules.js';
import {tendBeds} from './farming.js';
import {RESTORATIONS,restorePlace} from './restoration.js';
import {prosperity,CROPS,PROFESSIONS,JOBS,jobStatus,deliver,sell,upgrade,upgradeCost} from './economy.js';
import {itemById} from './catalog.js';
import {cropStatus} from './core.js';
export function mountWork({get,commit,enter,toast}){
 const $=id=>document.getElementById(id);let tab='farm',homeId=null;
 const node=(tag,text,cls)=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;};
 const run=fn=>{try{const message=fn();commit();render();$('work-message').textContent=message;toast(message);}catch(e){$('work-message').textContent=e.message;}};
 function button(text,fn,disabled=false){const el=node('button',text);el.disabled=disabled;el.onclick=fn;return el;}
 function card(title,body){const el=node('article','','work-card');el.append(node('h3',title),node('p',body));return el;}
 function render(){const s=get();$('work-coins').textContent=`${prosperity(s).count} habits this week · ${s.economy.coins} copper`;$('work-tabs').replaceChildren();for(const[id,label]of [['farm','Garden'],['places','Restore']]){const b=button(label,()=>{tab=id;render();});b.classList.toggle('active',tab===id);$('work-tabs').append(b);}
 const list=$('work-list');list.replaceChildren();
 if(tab==='farm'){const beds=s.objects.filter(o=>o.type==='crop');list.append(node('p',`${beds.length} beds · ${beds.filter(o=>cropStatus(s,o)==='ready').length} ready. Tap a bed to plant, water or harvest it.`));for(const [i,plot]of farmPlots(s).entries()){const summary=['empty','thirsty','growing','ready'].map(status=>`${plot.filter(o=>cropStatus(s,o)===status).length} ${status}`).join(' · '),section=card(`Garden plot ${i+1} · ${plot.length} beds`,summary);section.classList.add('farm-plot');for(const[action,label]of [['plant','Plant empty beds'],['water','Water thirsty beds'],['harvest','Harvest ripe beds'],['compost','Add compost · 2 herbs + 1 mushroom / bed']])section.append(button(label,()=>run(()=>tendBeds(s,plot.map(o=>o.id),action))));const detail=node('details'),heading=node('summary','See crops & growth');detail.append(heading);for(const bed of plot){const seed=CROPS.find(c=>c.id===bed.crop?.kind);detail.append(node('p',`${seed?.name||'Empty bed'} · ${cropStatus(s,bed)}${bed.crop?.stage==='watered'?` · ${Math.max(0,growthTime(s,bed)-(s.progress-bed.crop.at))} habits left`:''}${bed.compost?' · enriched soil':''}${nearby(s,bed,'sprinkler',2)?' · irrigated':''}`));}section.append(detail);list.append(section);}for(const c of CROPS){const el=card(c.name,`${c.grow} completed habit${c.grow===1?'':'s'} to grow · harvest ${c.yield} · ${c.price} copper each`);el.style.setProperty('--crop',c.color);el.append(button(s.economy.seed===c.id?'✓ Plot seed':'Use for whole-plot planting',()=>{s.economy.seed=c.id;commit();render();},s.economy.seed===c.id));list.append(el);}list.append(button('Return to my garden',()=>$('work-dialog').close()));}
 if(tab==='places'){list.append(node('p','Place a site from Build → Restore, then bring it back in three stages.'));for(const r of RESTORATIONS){const sites=s.objects.filter(o=>o.type===r.id);if(!sites.length){list.append(card(r.name,'Place this site in your meadow to begin. It becomes '+itemById(r.result).name+'.'));continue;}for(const o of sites){const stage=o.restoration||0,el=card(r.name,`Stage ${stage+1}/3 · ${r.stages[stage]}`);el.append(node('p',`${r.thresholds[stage]} total habits (${s.progress} completed) · ${Object.entries(r.costs[stage]).map(([k,n])=>`${n} ${k}`).join(' · ')}`),button('Restore this stage',()=>run(()=>restorePlace(s,o.id))));list.append(el);}}}
 if(tab==='jobs'){list.append(node('p','Deliver supplies to the places you build. Each order returns after your next completed habit. No deadlines, missed-day penalties, or disappearing rewards.'));for(const j of JOBS){const status=jobStatus(s,j);const el=card(j.title,j.description);el.append(node('small',`${j.role} · ${itemById(j.place).name}`),node('p',Object.entries(j.cost).map(([k,n])=>`${Math.min(n,s.inventory[k])}/${n} ${k}`).join(' · ')),button(status==='building'?'Build '+itemById(j.place).name:status==='rest'?'New order after next habit':`Deliver · +${j.coins} copper · +3 XP`,()=>run(()=>deliver(s,j.id)),status!=='ready'));list.append(el);}}
 if(tab==='trade'){list.append(node('p','Sell a little of your harvest to fund room expansions, or keep ingredients for higher-paying village orders.'));for(const[k,n]of Object.entries(s.inventory)){const el=card(CROPS.find(c=>c.id===k)?.name||k,`${n} in your basket`);el.append(button(`Sell one · +${CROPS.find(c=>c.id===k)?.price||3} copper`,()=>run(()=>sell(s,k)),!n));list.append(el);}}
 if(tab==='skills'){for(const role of PROFESSIONS){const xp=s.economy.xp[role],level=Math.floor(xp/12)+1;const el=card(role,`Level ${level} · ${xp} experience`),meter=document.createElement('progress');meter.max=12;meter.value=xp%12;meter.setAttribute('aria-label',`${role}: ${xp%12} of 12 toward next level`);el.append(meter,node('small',`${12-xp%12} experience until level ${level+1}`));list.append(el);}list.append(node('p','Earn experience through harvests, gathering, fishing and village deliveries. Profession levels record your journey; all decoration unlocks remain tied to habits and stories.'));}}
 $('work-btn').onclick=()=>{render();$('work-dialog').showModal();};
 function renderUpgrade(){const s=get(),o=s.objects.find(o=>o.id===homeId);if(!o)return;const level=s.economy.upgrades[homeId]||0,cost=upgradeCost(s,homeId);$('upgrade-title').textContent=itemById(o.type).name;$('upgrade-description').textContent=`Room tier ${level+1} · ${10+level*2} × ${10+level*2} tiles. ${level===3?'Your building is fully expanded.':'Expand the interior by two tiles in each direction. All your furniture stays in place.'}`;$('upgrade-cost').textContent=level===3?'Ready to decorate.':`${cost.coins} copper (${s.economy.coins} owned) · ${cost.wood} wood (${s.inventory.wood}) · ${cost.stones} stones (${s.inventory.stones})`;$('upgrade-buy').disabled=level===3;$('upgrade-buy').textContent=level===3?'Fully expanded':`Build tier ${level+2}`;}
 $('upgrade-buy').onclick=()=>{try{const message=upgrade(get(),homeId);commit();renderUpgrade();$('upgrade-result').textContent=message;}catch(e){$('upgrade-result').textContent=e.message;}};
 $('upgrade-enter').onclick=()=>{$('upgrade-dialog').close();enter(homeId);};
 return {openUpgrade(id){homeId=id;$('upgrade-result').textContent='';renderUpgrade();$('upgrade-dialog').showModal();}};
}
