import {getWorkout,movements,research,duration} from './collection-data.js';
import {createSession} from './collection-session.js';
import {CollectionScene} from './collection-scene.js';
const $=id=>document.getElementById(id),id=new URLSearchParams(location.search).get('workout')??'dumbbells';
let w;try{w=getWorkout(id);}catch{location.replace('collection.html');throw Error('Unknown workout');}
const storagePrefix=new URLSearchParams(location.search).has('qc')?'spyr.qc.':'';
const engine=createSession(w),key=storagePrefix+`spyr.collection.${w.id}.v2`,historyKey=storagePrefix+'spyr.collection.history.v1',read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},write=(k,v)=>{try{v===null?localStorage.removeItem(k):localStorage.setItem(k,JSON.stringify(v));}catch{$('storage-status').hidden=false;}},fmt=n=>`${Math.floor(Math.max(0,Math.ceil(n))/60)}:${String(Math.max(0,Math.ceil(n))%60).padStart(2,'0')}`;
let artReady=false,easier=false,voice=false,lastSpoken=-1,lastClock=performance.now();
let s=engine.fresh(),started=false,previous=0,lastSave=0,lastSignature='',modalPaused=false,result=null;
const scene=new CollectionScene($('scene'),m=>{$('art-status').hidden=!m;$('art-status').textContent=m??'';});
$('studio').dataset.audio=String(!!w.audio);
document.title=w.title+' · SPYR Gym';$('overview').textContent=w.title.toUpperCase();$('trainer-name').textContent=w.trainerName;$('trainer-room').textContent=w.room;$('edition').textContent='VOL. '+String(w.number).padStart(2,'0');$('plan-title').textContent=w.title;$('plan-trainer').textContent=w.trainerName.toUpperCase()+' / '+w.category.toUpperCase();$('challenge').textContent=w.challenge;
$('progress').setAttribute('aria-valuemax',engine.stats(s).total);$('studio').style.setProperty('--movement-count',w.entries.length);
$('lineup').innerHTML=w.entries.map((e,i)=>`<li data-key="${e.key}"><b>${String(i+1).padStart(2,'0')}</b><div>${movements[e.key].name}<small>${e.seconds?e.seconds+' SEC':e.sets+' × '+e.reps}</small></div></li>`).join('');
$('plan-list').innerHTML=w.entries.map(e=>`<div class="plan-row"><strong>${movements[e.key].name}</strong><span>${e.seconds?`${w.mode==='sets'?e.sets:w.rounds} × ${e.seconds}s`:`${e.sets} × ${e.reps}`}<small> / ${e.rest}s rest</small></span></div>`).join('');
$('plan-description').textContent=(w.mode==='sets'?'Complete each exercise’s sets before moving on.':'Complete the circuit '+w.rounds+' time'+(w.rounds===1?'':'s')+'.')+(['yoga','pilates'].includes(w.category)?' Settle into your breathing before starting. ':' Warm up first with easy movement and lighter practice sets. ')+(w.changes??'')+(w.audio?' Set up on a safe route before starting. This browser does not track GPS or distance. Keep the session open; locked-screen audio depends on your browser.':'')+(w.category==='heavy'?' Alternate A and B with a rest day between sessions. Begin with a manageable load, use warm-up sets, and increase by the smallest suitable increment only after every prescribed rep is controlled. Use rack safeties and a spotter for bench press.':'');
$('plan-sources').innerHTML=w.sources.map(k=>`<p><a href="${research[k].url}" target="_blank" rel="noopener">${research[k].title} ↗</a></p>`).join('')+'<p class="fine">Original SPYR session. Sources inform the format; no affiliation or endorsement.</p>';
function persist(){if(started&&s.status==='active')write(key,s);}
function openModal(id){modalPaused=s.paused;s.paused=true;persist();render();$(id).showModal();}
for(const id of ['guide-dialog','plan-dialog','log-dialog','exit-dialog'])$(id).addEventListener('close',()=>{s.paused=modalPaused;lastClock=performance.now();persist();render();});
function start(skip=false){if(!artReady)return;lastClock=performance.now();started=true;s.paused=false;if(skip&&engine.current(s).kind==='warmup')engine.advance(s);persist();render();}
function finish(){if(result)return;scene.set(engine.plan.at(-1).key,'rest',true,1);window.speechSynthesis?.cancel();const stats=engine.stats(s);result={...structuredClone(s),date:new Date().toISOString(),title:w.title,trainer:w.trainer,complete:stats.completed===stats.total,stamp:stats.completed===stats.total?w.stamp:null};let history=read(historyKey,[]);if(!Array.isArray(history))history=[];history=history.filter(h=>h.logId!==result.logId);history.push(result);write(historyKey,history);write(key,null);$('result-sets').innerHTML=`${stats.completed}<span>${w.mode==='sets'?'SETS':'INTERVALS'}</span>`;$('result-time').textContent=fmt(s.elapsed);$('result-copy').textContent=w.title+' · '+w.trainerName;$('stamp').textContent=result.stamp?'STAMP EARNED · '+result.stamp:'SESSION SAVED · '+stats.completed+' / '+stats.total+' completed';$('result-dialog').showModal();window.dispatchEvent(new CustomEvent('spyr:workout-complete',{detail:structuredClone(result)}));if(window.parent!==window){try{window.parent.postMessage({type:'spyr:workout-complete',record:structuredClone(result)},location.origin);}catch{}}}
function changed(){if(s.status==='finished')finish();else{persist();render();}}
$('action').onclick=()=>{if(!started)return start();if(s.paused){s.paused=false;lastClock=performance.now();return changed();}engine.advance(s,engine.current(s).kind==='work'?'early':'complete');changed();};
$('secondary').hidden=false;$('secondary').onclick=()=>start(true);
$('pause').onclick=()=>{s.paused=!s.paused;lastClock=performance.now();if(s.paused)window.speechSynthesis?.cancel();changed();};$('extra').onclick=()=>{if(!s.paused){s.remaining+=30;changed();}};
$('guide').onclick=()=>{const m=movements[engine.current(s).key],ref=m.source??research[w.sources[0]];$('guide-title').textContent=m.name;$('guide-copy').textContent=(m.setup?m.setup+' ': '')+m.cue;$('guide-tip').textContent=m.easy;$('guide-source').href=ref.url;$('guide-source').textContent=ref.title+' ↗';openModal('guide-dialog');};
$('plan').onclick=$('overview').onclick=()=>openModal('plan-dialog');
$('log').onclick=()=>{const p=engine.current(s),m=movements[p.key];$('log-set').textContent=m.name+' / SET '+p.set;$('weight-label').firstChild.textContent=/dumbbell/i.test(m.name)?'Per dumbbell':'Load (0 for bodyweight)';$('reps').value='';$('weight').value='';$('unit').value=read('spyr.gym.unit.v1','lb');openModal('log-dialog');};
$('log-form').onsubmit=e=>{e.preventDefault();if(!$('log-form').reportValidity())return;const log={reps:Number($('reps').value),weight:Number($('weight').value),unit:$('unit').value,rir:Number($('rir').value)};if(!Number.isInteger(log.reps)||log.reps<0||log.reps>100||!Number.isFinite(log.weight)||log.weight<0||log.weight>2000||!['lb','kg'].includes(log.unit)||!Number.isInteger(log.rir)||log.rir<0||log.rir>5)return;write('spyr.gym.unit.v1',log.unit);modalPaused=false;$('log-dialog').close();engine.advance(s,'complete',log);changed();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('studio').requestFullscreen?.();}catch{}};
function leave(){if(window.parent!==window){window.parent.postMessage({type:'spyr:exit'},location.origin);}else location.assign('index.html#category='+w.category);}
$('exit').onclick=()=>started?openModal('exit-dialog'):leave();$('save-exit').onclick=()=>{s.paused=true;persist();leave();};
function render(){if(s.status!=='active')return;const p=engine.current(s),m=movements[p.key],stats=engine.stats(s),phase=!started?'ready':p.kind==='lift'||p.kind==='work'?'lift':p.kind,signature=[phase,s.index,s.paused].join(':');$('studio').dataset.phase=phase;$('progress-fill').style.width=stats.processed/stats.total*100+'%';$('progress').setAttribute('aria-valuenow',stats.completed);$('session-count').textContent=started?`${stats.completed} / ${stats.total} ${w.mode==='sets'?'SETS':'INTERVALS'} COMPLETE`:`${stats.total} ${w.mode==='sets'?'WORKING SETS':'WORK INTERVALS'}`;$('elapsed').textContent=started?fmt(s.elapsed)+' ELAPSED':duration(w).toUpperCase();$('pause').hidden=!started;$('pause').textContent=s.paused?'Resume':'Pause';$('target').textContent=!started?String(w.entries.length):p.kind==='lift'?p.reps:fmt(s.remaining);$('extra').disabled=s.paused;
 if(signature!==lastSignature){lastSignature=signature;$('movement').textContent=!started?w.title:phase==='warmup'?'Find your rhythm.':phase==='rest'?'Breathe. Reset.':phase==='cooldown'?'Let it settle.':m.name;$('phase').textContent=s.paused&&started?'SESSION PAUSED':!started?`SESSION ${String(w.number).padStart(2,'0')} / ${w.category.toUpperCase()}`:phase==='lift'?(w.mode==='sets'?`SET ${p.set} / ${p.sets}`:`ROUND ${p.round} / ${w.rounds}`)+(p.side?' · '+p.side.toUpperCase():''):phase.toUpperCase();$('cue').textContent=!started?w.challenge:phase==='lift'?(easier&&['jack','climber'].includes(p.key)?movements.kaiMarch.brief:m.brief):phase==='warmup'?(w.audio?(w.category==='bike'?'Start with five minutes of easy spinning. Check your saddle and resistance.':'Walk easily for five minutes before the first effort.'):['yoga','pilates'].includes(w.category)?'Settle your breathing and ease into a comfortable position.':'Easy movement, a couple of light practice sets. No rush.'):phase==='rest'?(['yoga','pilates'].includes(w.category)?'Relax your effort. Breathe comfortably.':'Set the equipment down. Breathe and prepare for the next effort.'):(['yoga','pilates'].includes(w.category)?'Rest comfortably. Let your breath settle.':w.category==='bike'?'Ease the resistance and spin gently. Let your breathing settle.':'Walk gently or rest comfortably. Let your breathing settle.');$('target-label').textContent=!started?'EXERCISES':p.kind==='lift'?'REPS':'REMAINING';$('set-number').textContent=!started?String(stats.total):phase==='lift'?(w.mode==='sets'?`${p.set} / ${p.sets}`:`${p.round} / ${w.rounds}`):String(stats.completed);$('set-label').textContent=!started?'WORK STATIONS':phase==='lift'?(w.mode==='sets'?'SET':'ROUND'):'COMPLETE';$('action-label').textContent=!started?'Enter session':s.paused?'Resume':p.kind==='lift'?'Set complete':p.kind==='work'?'End interval':p.kind==='warmup'?'Begin workout':p.kind==='cooldown'?'Finish session':'Start next effort';$('secondary').hidden=started;$('guide').hidden=phase!=='lift';$('log').hidden=p.kind!=='lift'||!started||s.paused;$('extra').hidden=!started||!['rest','warmup'].includes(p.kind);$('set-track').innerHTML=Array.from({length:w.mode==='sets'?(p.sets??0):w.rounds},(_,i)=>`<span class="${i<(w.mode==='sets'?p.set-1:p.round-1)?'done':i===(w.mode==='sets'?p.set-1:p.round-1)?'current':''}"></span>`).join('');const next=engine.plan.slice(s.index+1).find(p=>['work','lift'].includes(p.kind));$('next').textContent=next?'NEXT / '+movements[next.key].name.toUpperCase():'COOL DOWN & COLLECT YOUR STAMP';$('footer-note').textContent=phase==='rest'?'Rest is part of the work.':'Steady beats strong.';$('lineup').querySelectorAll('li').forEach(li=>li.classList.toggle('active',li.dataset.key===p.key));}
 $('easier').hidden=!(started&&['jack','climber'].includes(p.key));$('easier').textContent=easier?'Return to exercise':'Switch to marching';
 s.variation=easier&&['jack','climber'].includes(p.key)?'kaiMarch':null;
 scene.set(s.variation??p.key,started&&(phase==='lift'||w.audio&&['warmup','cooldown'].includes(phase))?'work':'rest',s.paused||!started,stats.processed/stats.total,p.side);
 if(started&&!s.paused&&voice&&s.index!==lastSpoken){lastSpoken=s.index;speak((p.kind==='rest'?'Rest':p.kind==='warmup'?'Warm up':p.kind==='cooldown'?'Cool down':m.name)+(p.side?'. '+p.side:'')+(p.seconds?'. '+Math.round(p.seconds)+' seconds.':''));}}
const saved=read(key,null);$('resume').onclick=()=>{s=structuredClone(saved);$('resume-dialog').close();start();};$('restart').onclick=()=>{write(key,null);$('resume-dialog').close();render();};if(engine.valid(saved)){$('resume-copy').textContent=`${engine.stats(saved).completed} efforts complete · ${movements[engine.current(saved).key].name}`;$('resume-dialog').showModal();}
$('export-log').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=w.id+'-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('pagehide',()=>{s.paused=true;persist();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!w.audio){s.paused=true;persist();render();}if(!w.audio)lastClock=performance.now();previous=0;});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!document.querySelector('dialog[open]')&&!['INPUT','SELECT','BUTTON'].includes(document.activeElement?.tagName)){e.preventDefault();if(started){s.paused=!s.paused;changed();}}});
function speak(text){if(!voice||!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.92;window.speechSynthesis.speak(utterance);}
$('voice').hidden=!('speechSynthesis' in window);$('voice').onclick=()=>{voice=!voice;$('voice').textContent=voice?'Audio cues on':'Audio cues off';$('voice').setAttribute('aria-pressed',voice);if(voice)speak('Audio cues on. '+w.title);else window.speechSynthesis.cancel();};
$('easier').onclick=()=>{easier=!easier;lastSignature='';render();};
$('result-home').onclick=e=>{e.preventDefault();leave();};
$('action').disabled=true;$('secondary').disabled=true;render();scene.load(w).then(()=>{artReady=true;$('action').disabled=false;$('secondary').disabled=false;render();}).catch(()=>{$('art-status').hidden=false;$('art-status').textContent='Artwork unavailable. Reload to retry before starting.';});
function advanceClock(now){const dt=Math.max(0,(now-lastClock)/1000);lastClock=now;if(started&&s.status==='active'){const oldIndex=s.index;engine.tick(s,dt);if(s.status==='finished')finish();else render();if(oldIndex!==s.index||now-lastSave>2000){persist();lastSave=now;}}}
function frame(now){const dt=previous?Math.min(.1,(now-previous)/1000):0;previous=now;if(!document.hidden){advanceClock(now);scene.update(dt);}requestAnimationFrame(frame);}requestAnimationFrame(frame);
// Timers reconcile elapsed time when a background tab is throttled. Browsers may
// still suspend sound while locked; the plan explains this limitation.
setInterval(()=>{if(document.hidden&&w.audio)advanceClock(performance.now());},1000);
