import {categories,collection,movements,duration} from './collection-data.js';
const $=id=>document.getElementById(id);let selected=null;
const image=(name,fallback)=>`<img src="assets/${name}.webp" alt="" loading="lazy" onerror="this.onerror=null;this.src='assets/${fallback}.webp'">`;
$('category-grid').innerHTML=categories.map((c,i)=>`<a class="category-tile" href="#category=${c.id}" aria-label="${c.name}, ${collection.filter(w=>w.category===c.id).length} workouts">${image(c.image,c.fallback)}<div class="tile-top"><span class="tile-number">0${i+1}</span><span>${collection.filter(w=>w.category===c.id).length} SESSIONS</span></div><div class="tile-bottom"><h2>${c.name.replace(' & ',' &<br>')}</h2><div class="tile-meta"><span>${c.equipmentNote??'Open the room'}</span><span class="tile-enter" aria-hidden="true">→</span></div></div></a>`).join('');
$('index-body').innerHTML=collection.map(w=>`<tr><td>${categories.find(c=>c.id===w.category).name}</td><td><a href="#workout=${w.id}">${w.title}</a></td><td>${duration(w)}</td><td>${w.equipment}</td><td>${w.trainerName}</td></tr>`).join('');
$('chart-toggle').onclick=()=>{const show=$('workout-index').hidden;$('workout-index').hidden=!show;$('chart-toggle').setAttribute('aria-expanded',show);if(show)$('workout-index').scrollIntoView({behavior:'smooth'});};
$('back-categories').onclick=()=>{location.hash='';};
const player=document.createElement('section');player.className='session-overlay';player.hidden=true;player.setAttribute('aria-label','Workout session');player.innerHTML='<iframe title="SPYR GYM workout" allow="fullscreen; autoplay" allowfullscreen></iframe>';document.body.append(player);const frame=player.querySelector('iframe');
function route(){const params=new URLSearchParams(location.hash.slice(1)),workout=collection.find(w=>w.id===params.get('workout'));if(workout){selected=workout.category;player.hidden=false;document.querySelector('.gym-home').inert=true;document.body.style.overflow='hidden';let url=workout.route??'session.html?workout='+workout.id;if(new URLSearchParams(location.search).has('qc')&&!workout.route)url+='&qc=1';if(frame.dataset.route!==url){frame.dataset.route=url;frame.src=url;}return;}player.hidden=true;document.querySelector('.gym-home').inert=false;document.body.style.overflow='';if(frame.dataset.route){frame.removeAttribute('src');delete frame.dataset.route;}const c=categories.find(c=>c.id===params.get('category'));$('categories').hidden=!!c;$('category-detail').hidden=!c;if(c){selected=c.id;$('category-title').textContent=c.name;$('category-kicker').textContent='Room '+String(categories.indexOf(c)+1).padStart(2,'0')+' of '+categories.length;$('category-description').textContent=c.description;$('workout-grid').innerHTML=collection.filter(w=>w.category===c.id).map(w=>`<article class="workout-card">${image(w.background,w.background).replace('<img','<img class="workout-image"')}<div class="workout-info"><p class="workout-meta">${duration(w).toUpperCase()} · ${w.trainerName.toUpperCase()}</p><h2>${w.title}</h2><p>${w.entries.map(e=>movements[e.key].name).join(' · ')}</p><p>${w.equipment}</p><a class="enter-workout" href="#workout=${w.id}">Start session <span aria-hidden="true">→</span></a></div></article>`).join('');$('category-title').focus({preventScroll:true});}window.scrollTo(0,0);}
frame.addEventListener('load',()=>{try{const path=frame.contentWindow.location.pathname;if(frame.dataset.route&&(/\/(index|collection|gym)\.html$/.test(path)||path==='/'))location.hash='category='+(selected??'gym');}catch{}});
const embedded=window.parent!==window;window.addEventListener('message',e=>{if(e.source!==frame.contentWindow||e.origin!==location.origin)return;if(e.data?.type==='spyr:exit')location.hash='category='+(selected??'gym');if(e.data?.type==='spyr:workout-complete'&&embedded){try{window.parent.postMessage({type:'spyr:gym-complete',record:e.data.record},location.origin);}catch{}}});if(embedded){const back=document.createElement('button');back.type='button';back.className='host-back';back.setAttribute('aria-label','Back to SPYR');back.innerHTML='&larr; Back to SPYR';back.onclick=()=>{try{window.parent.postMessage({type:'spyr:gym-exit'},location.origin);}catch{}};document.querySelector('.home-header').prepend(back);document.body.classList.add('embedded');}
window.addEventListener('hashchange',()=>{if(document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches)document.startViewTransition(route);else route();});route();
