export const reviewedForms={
 'back-squat':{cue:'Set the rack catches below shoulder height and safeties just below the bottom of your squat. Rest the bar on your upper traps, grip evenly, then step clear of the hooks. Brace and lower with your whole foot planted, knees following your toes. Stand smoothly.',tip:'Keep the bar over your midfoot. Choose a depth you can control without rounding your back or lifting your heels.',url:'https://www.puregym.com/exercises/legs/quad-exercises/squats/barbell-back-squat/',label:'PureGym · Barbell back squat'},
 'db-rdl':{cue:'Stand with feet about hip-width apart and a dumbbell in each hand. Soften your knees, then send your hips backward while keeping the weights close to your legs. Stop at a comfortable hamstring stretch with a neutral spine, then drive your hips forward to stand.',tip:'Let your head follow your torso. Keep a small, steady knee bend; avoid turning the hinge into a squat or leaning back at the top.',url:'https://www.acefitness.org/continuing-education/certified/may-2025/8865/the-ace-do-it-better-series-the-romanian-deadlift/',label:'ACE · Romanian deadlift'},
 'leg-extension':{cue:'Adjust the seat so your knees line up with the machine pivot. Sit against the backrest with knees bent about 90 degrees and the roller in front of your lower shins, above the ankles. Hold the side handles, extend your legs smoothly, pause, then lower slowly.',tip:'Keep your hips and back supported. Avoid kicking the weight or snapping your knees into lockout. Choose a load you can lift through a controlled range.',url:'https://www.puregym.com/exercises/legs/quad-exercises/leg-extensions/',label:'PureGym · Leg extension'},
 'calf-raise':{cue:'Stand with your feet hip-width apart, holding the dumbbells by your sides. Keep your knees soft and torso tall. Lift your heels through the balls of your feet, pause, then lower slowly to the floor.',tip:'Keep your ankles aligned rather than rolling outward. Use a supported or seated variation if balance limits your control.',url:'https://www.puregym.com/exercises/legs/calf-exercises/calf-raises/',label:'PureGym · Standing calf raise'},
 'reverse-crunch':{cue:'Lie on your back with your head resting and arms beside you. Bend your knees to roughly a right angle. Brace and gently roll your pelvis toward your ribs so your hips lift slightly, then lower slowly.',tip:'Use a small controlled curl. Avoid throwing your legs overhead or lifting your head. This is a bodyweight movement; added load can stay at zero.',url:'https://www.puregym.com/exercises/abs/reverse-crunches/',label:'PureGym · Reverse crunch'},
 'db-bench':{cue:'Lie lengthwise on the bench with your head, shoulders and hips supported and both feet flat. Hold the dumbbells beside your chest with wrists above elbows. Press up over the chest, then lower slowly through a comfortable range.',tip:'Keep your elbows slightly tucked and your hips on the pad. Avoid bouncing or letting your wrists fold back.',url:'https://www.acefitness.org/resources/everyone/exercise-library/19/chest-press/',label:'ACE · Dumbbell chest press'},
 'db-overhead':{cue:'Sit against the backrest with feet flat and your torso braced. Start at shoulder height with wrists above elbows and elbows slightly forward. Press overhead together, then lower under control.',tip:'Keep your back supported throughout. Avoid arching your lower back or clashing the dumbbells together.',url:'https://www.acefitness.org/resources/everyone/exercise-library/45/seated-overhead-press/',label:'ACE · Seated overhead press'},
 'lateral-raise':{cue:'Stand tall with soft knees and a slight elbow bend. Raise the dumbbells out to the sides, slightly forward of your torso, until around shoulder height. Lower slowly with neutral wrists.',tip:'Use a load you can lift without swinging or shrugging. Keep your head and torso steady.',url:'https://www.acefitness.org/resources/everyone/exercise-library/26/lateral-raise/',label:'ACE · Lateral raise'},
 'pressdown':{cue:'Face the high cable with feet planted, knees soft and a small, steady forward lean. Keep your upper arms beside your ribs. Extend your elbows to bring the bar toward the thighs, pause, then return slowly.',tip:'Move at the elbows. Avoid pulling your upper arms backward or leaning farther forward to finish the rep.',url:'https://www.puregym.com/exercises/arms-and-shoulders/tricep-extension/tricep-pushdowns/',label:'PureGym · Triceps pushdown'},
 'lat-pulldown':{cue:'Sit centered with feet flat. Secure the pad across the tops of your thighs, just above the knees. Begin with arms overhead and a steady, slightly reclined torso. Pull elbows down beside your ribs, bringing the bar in front of you toward the upper chest. Return slowly.',tip:'The pull is mainly downward. Keep the bar clear of your face and avoid swinging backward to finish the rep.',url:'https://www.acefitness.org/resources/everyone/exercise-library/158/seated-lat-pulldown/',label:'ACE · Lat pulldown'},
 'cable-row':{cue:'Sit along the center of the bench, facing the cable. Place both soles against the foot supports with knees softly bent. Keep your spine neutral and chest lifted. Pull the handle toward your stomach, elbows close to the ribs. Pause, then extend under control.',tip:'Keep your hips supported and feet planted throughout; avoid rocking your torso to move the load.',url:'https://www.acefitness.org/resources/everyone/exercise-library/48/seated-row/',label:'ACE · Seated cable row'},
 'rear-delt':{cue:'Stand with soft knees and hinge at your hips. Hold a steady back and let the dumbbells hang below the shoulders. With a slight, consistent elbow bend, open your arms out to the sides, then lower slowly.',tip:'Use light weights. Keep the movement in the shoulders rather than turning it into a row or shrug.',url:'https://www.puregym.com/exercises/arms-and-shoulders/rear-delt-exercises/rear-delt-flyes/',label:'PureGym · Rear-delt fly'},
 'db-curl':{cue:'Stand tall with knees relaxed and elbows close to your sides. Curl the dumbbells toward your shoulders with smooth wrists and controlled elbows. Lower through a comfortable full range.',tip:'Keep your back and upper arms steady. Reduce the weight if you need to swing.',url:'https://www.mayoclinic.org/healthy-lifestyle/fitness/multimedia/biceps-curl/vid-20084675',label:'Mayo Clinic · Dumbbell curl'}
};
