const files=['squat','pushup','lunge','row','jack','march'];
export class Scene {
 constructor(canvas,onStatus){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.frames={};this.background=null;this.onStatus=onStatus;this.time=0;this.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;this.move={asset:'squat'};this.idle=false;this.paused=false;}
 async load(){try{const image=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Could not load '+src));i.src=src;});this.background=await image('assets/woodland-gym.webp');this.draw();await Promise.all(files.map(async name=>{const im=await image(`assets/${name}.webp`);this.frames[name]=this.extract(im,name);}));this.onStatus(null);this.draw();return true;}catch(e){this.onStatus('The artwork could not load. Reload to retry; written workout controls still work.');return false;}}
 extract(im,name){const frames=[];for(let i=0;i<6;i++){let x,y,w,h;if(name==='pushup'){x=(i%2)*768;y=i<2?0:i<4?355:700;w=768;h=i<2?330:i<4?300:270;}else{x=(i%3)*512;y=Math.floor(i/3)*512;w=h=512;}const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,x,y,w,h,0,0,w,h);const d=ctx.getImageData(0,0,w,h),p=d.data;
 if(name!=='pushup'){for(let k=0;k<p.length;k+=4){const r=p[k],g=p[k+1],b=p[k+2];if(r>145&&b>135&&g<130&&r-g>65&&b-g>65)p[k+3]=0;}}
 else{ // Flood-fill only connected backdrop so the cream shirt is retained.
 const seen=new Uint8Array(w*h),queue=new Int32Array(w*h);let head=0,tail=0;
 const visit=n=>{if(n<0||n>=w*h||seen[n])return;seen[n]=1;const k=n*4;if(p[k]>205&&p[k+1]>199&&p[k+2]>175&&Math.max(p[k],p[k+1],p[k+2])-Math.min(p[k],p[k+1],p[k+2])<48){p[k+3]=0;queue[tail++]=n;}};
 for(let xx=0;xx<w;xx++){visit(xx);visit((h-1)*w+xx);}for(let yy=0;yy<h;yy++){visit(yy*w);visit(yy*w+w-1);}while(head<tail){const n=queue[head++];if(n%w)visit(n-1);if(n%w<w-1)visit(n+1);visit(n-w);visit(n+w);}}
 let bottom=0,left=w,right=0,top=h;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){if(p[(yy*w+xx)*4+3]>128){bottom=Math.max(bottom,yy);top=Math.min(top,yy);left=Math.min(left,xx);right=Math.max(right,xx);}}ctx.putImageData(d,0,0);frames.push({c,bottom,left,right,top});}return frames;}
 set(move,idle=false,paused=false){if(this.move.asset!==move.asset||this.move.mirror!==move.mirror||this.move.hold!==move.hold)this.time=0;this.move=move;this.idle=idle;this.paused=paused;this.draw();}
 update(dt){if(this.motion&&!this.paused&&!this.idle&&Number.isFinite(dt))this.time+=Math.max(0,dt);this.draw();}
 draw(){const c=this.ctx;if(!c)return;c.clearRect(0,0,1200,800);if(this.background)c.drawImage(this.background,0,0,1200,800);else{c.fillStyle='#e0e5d0';c.fillRect(0,0,1200,800);}const name=this.idle?'march':this.move.asset,frames=this.frames[name];if(!frames)return;let sequence=['squat','row','pushup'].includes(name)?[0,1,2,3,4,5,4,3,2,1]:name==='lunge'?[0,1,3,2,3,4,5]:name==='jack'?[0,1,2,3,2,4,5]:[2,1,0,1,2,4,3,4];const speed=name==='march'?.18:name==='jack'?.17:.22;let ix=sequence[Math.floor(this.time/speed)%sequence.length];if(this.idle)ix=2;if(this.move.hold&&!this.idle)ix=0;const f=frames[ix];const scale=name==='pushup'?1.12:name==='row'?.98:.96;const ground=685;const anchor=name==='lunge'?350:name==='row'?280:name==='pushup'?385:270;const mirror=!!this.move.mirror;
 c.save();c.translate(600,ground);if(mirror)c.scale(-1,1);c.fillStyle='#283e2829';c.beginPath();c.ellipse(0,0,name==='pushup'?320:name==='row'?190:90,13,0,0,Math.PI*2);c.fill();c.imageSmoothingEnabled=false;c.drawImage(f.c,-anchor*scale,-f.bottom*scale,f.c.width*scale,f.c.height*scale);c.restore();}
}
