import {gymSpriteSpecs,prepareGymSprite,drawGymSprite} from './gym-sprites.js';
import {Scene} from './scene.js';
const cache=new Map();export function loadImage(name){if(!cache.has(name))cache.set(name,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>{cache.delete(name);reject(Error('Artwork unavailable: '+name));};im.src=`assets/${name}.webp`;}));return cache.get(name);}
export const atlasRects={'01':[[0,0,362,370],[362,0,362,370],[724,0,362,370],[0,370,362,354],[362,370,362,354],[724,370,362,354],[0,724,362,364],[362,724,362,364],[0,1088,543,180],[543,1088,543,180],[0,1268,543,180],[543,1268,543,180]],'03':Array.from({length:12},(_,i)=>[(i%3)*362,[0,392,795,1086][Math.floor(i/3)],362,[392,403,291,362][Math.floor(i/3)]]),'04':Array.from({length:12},(_,i)=>[(i%3)*362,[0,360,670,985][Math.floor(i/3)],362,[360,310,315,463][Math.floor(i/3)]])};
atlasRects['gym-chest-back']=Array.from({length:12},(_,i)=>[(i%3)*362,[0,362,724,1055][Math.floor(i/3)],362,[362,362,331,393][Math.floor(i/3)]]);
atlasRects['gym-shoulders-arms']=Array.from({length:12},(_,i)=>[(i%3)*362,[0,362,713,1070][Math.floor(i/3)],362,[362,351,357,378][Math.floor(i/3)]]);atlasRects['gym-shoulders-arms'][3]=[0,362,380,351];atlasRects['gym-shoulders-arms'][4]=[380,362,344,365];
atlasRects['gym-legs-core']=Array.from({length:12},(_,i)=>[(i%3)*362,[0,390,712,1064][Math.floor(i/3)],362,[390,322,352,384][Math.floor(i/3)]]);

export function extractAtlas(im,id){const frames=[];for(let i=0;i<(id==='gym-lat-pulldown'?2:12);i++){const rect=atlasRects[id]?.[i]??(id==='gym-lat-pulldown'?[i*im.width/2,0,im.width/2,im.height]:[(i%3)*im.width/3,Math.floor(i/3)*im.height/4,im.width/3,im.height/4]);const [x,y,w,h]=rect,c=document.createElement('canvas');const factor=id==='gym-lat-pulldown'?Math.min(1,400/h):1;c.width=Math.round(w*factor);c.height=Math.round(h*factor);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,x,y,w,h,0,0,c.width,c.height);const d=ctx.getImageData(0,0,c.width,c.height),p=d.data;for(let k=0;k<p.length;k+=4)if((p[k]>220&&p[k+1]<35&&p[k+2]<35)||(id==='gym-lat-pulldown'&&p[k+3]<220))p[k+3]=0;ctx.putImageData(d,0,0);let left=c.width,right=0,top=c.height,bottom=0;for(let yy=0;yy<c.height;yy++)for(let xx=0;xx<c.width;xx++)if(p[(yy*c.width+xx)*4+3]>120){left=Math.min(left,xx);right=Math.max(right,xx);top=Math.min(top,yy);bottom=Math.max(bottom,yy);}const normalized=document.createElement('canvas');normalized.width=c.width;normalized.height=512;normalized.getContext('2d').drawImage(c,0,500-bottom);frames.push({c:normalized,left,right,top:top+500-bottom,bottom:500});}return frames;}
export class TrainingScene{
 constructor(canvas,onStatus){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.rig=new Scene(canvas,()=>{});this.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;this.paused=false;this.time=0;this.move=null;this.course=null;this.frames={};this.progress=0;this.onStatus=onStatus;this.loadId=0;this.gymAnimations={};}
 async load(course){this.course=course;this.frames={};this.bg=null;this.time=0;this.gymAnimations={};const id=++this.loadId;this.onStatus('Preparing your training space…');if(course.atlas?.startsWith('gym-')){try{const [bg,...gear]=await Promise.all([loadImage(course.background),...(Object.keys(course.moves).some(move=>gymSpriteSpecs[move]?.gear||gymSpriteSpecs[move]?.attachment)?['motion-equipment','motion-leg-equipment','motion-press-tower'].map(loadImage):[])]);if(id!==this.loadId)return;this.bg=bg;await Promise.all(Object.keys(course.moves).map(async move=>{const spec=gymSpriteSpecs[move];const [im,extra]=await Promise.all([loadImage(spec.file),spec.extra?loadImage(spec.extra):null]);if(id===this.loadId)this.gymAnimations[move]=prepareGymSprite(move,im,gear,extra);}));if(id===this.loadId)this.onStatus(null);}catch{if(id===this.loadId)this.onStatus('Animation could not load. Reload to retry.');}return;}const files=course.atlas?[course.atlas]:[...new Set(Object.values(course.moves).flatMap(m=>[m.asset,...(m.combo??[])]))];const results=await Promise.allSettled([loadImage(course.background).then(im=>{if(id===this.loadId)this.bg=im;}),...files.map(async name=>{const im=await loadImage(name);if(id!==this.loadId)return;this.frames[name]=course.atlas?extractAtlas(im,course.atlas.startsWith('trainer-')?course.trainer:course.atlas):this.rig.extract(im,name);})]);if(id===this.loadId&&course.atlas==='gym-chest-back'&&this.frames[course.atlas]){try{const strip=extractAtlas(await loadImage('gym-lat-pulldown'),'gym-lat-pulldown');if(id===this.loadId){this.frames[course.atlas][2]=strip[0];this.frames[course.atlas][3]=strip[1];}}catch{results.push({status:'rejected'});}}if(id===this.loadId)this.onStatus(results.some(r=>r.status==='rejected')?'Some artwork could not load. Written guidance is available; reload to retry.':null);}
 set(move,kind,paused,progress,side=''){this.side=side;if(this.move!==move||this.kind!==kind){this.move=move;this.time=0;}this.kind=kind;this.paused=paused;this.progress=progress;}
 update(dt){if(!this.paused&&this.motion&&Number.isFinite(dt))this.time+=Math.max(0,dt);this.draw();}
 draw(){if(!this.course)return;const c=this.ctx,rect=this.canvas.getBoundingClientRect(),w=Math.max(1,Math.round(rect.width)),h=Math.max(1,Math.round(rect.height));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}c.clearRect(0,0,w,h);c.fillStyle='#16392e';c.fillRect(0,0,w,h);c.imageSmoothingEnabled=false;const isGym=this.course.atlas?.startsWith('gym-');const cinematic=this.course.presentation==='cinematic';const floor=cinematic?h*(w<650?(this.course.mobileFloor??.65):.76):h*(isGym?(w<650?.57:.68):(w<650?.62:.72));if(this.bg){const scale=Math.max(w/this.bg.width,h/this.bg.height)*(this.course.backgroundZoom??1);const bh=this.bg.height*scale;const y=Math.min(0,Math.max(h-bh,floor-bh*this.course.ground));c.drawImage(this.bg,(w-this.bg.width*scale)/2,y,this.bg.width*scale,bh);}c.fillStyle=`rgba(4,26,30,${.27-this.progress*.12})`;c.fillRect(0,0,w,h);const m=this.course.moves[this.move];if(!m)return;if(isGym){const anim=this.gymAnimations[this.move];if(anim){c.save();if(this.side==='Left side'){const x=w*(cinematic&&w>=900?.57:.5);c.translate(x*2,0);c.scale(-1,1);}drawGymSprite(c,anim,this.time,this.motion&&this.kind==='work',w*(cinematic&&w>=900?.57:.5),floor,Math.min(h*(cinematic?(w<650?.34:.47):.46)/405,w*(cinematic?.86:.83)/(cinematic?460:640)));c.restore();}return;}let f,fs,name=m.asset;const resting=this.kind==='rest';if(this.course.atlas){fs=this.frames[this.course.atlas];if(!fs)return;const slot=resting&&!this.course.atlas.startsWith('gym-')?this.course.idleSlot:m.slot;let pose=this.course.atlas.startsWith('gym-')||!this.motion||m.hold||resting?0:Math.floor(this.time/.8)%2;f=fs[slot*2+pose];}else{if(resting||m.instructionOnly)name=this.course.trainer==='02'?'trainer02-march':'march';else if(m.combo)name=m.combo[Math.floor(this.time/.96)%m.combo.length];fs=this.frames[name];if(!fs)return;const seq=name==='front-squat'?[0,1,2,3,2,1]:[0,1,2,3,4,5,4,3,2,1];let i=seq[Math.floor(this.time/(name==='front-squat'?.5:name.includes('box')?.16:.35))%seq.length];if(!this.motion||resting||m.instructionOnly)i=name.endsWith('march')?2:0;if(m.hold)i=m.holdFrame??0;f=fs[i];}if(!f)return;
 // Render supplied raster frames at a fixed world anchor; never advance along the room.
 const group=this.course.atlas?fs.slice((resting&&!this.course.atlas.startsWith('gym-')?this.course.idleSlot:m.slot)*2,(resting&&!this.course.atlas.startsWith('gym-')?this.course.idleSlot:m.slot)*2+2):fs;const left=Math.min(...group.map(f=>f.left)),right=Math.max(...group.map(f=>f.right)),top=Math.min(...group.map(f=>f.top)),bottom=Math.max(...group.map(f=>f.bottom));const maxHeight=this.course.atlas?Math.max(...fs.map(f=>f.bottom-f.top)):cinematic?Math.max(...Object.values(this.frames).flat().map(f=>f.bottom-f.top)):400;const scale=Math.min(h*(cinematic&&w<650?.32:.42)/maxHeight,w*.68/(right-left||1));const center=(left+right)/2,x=w*(this.course.centered?(cinematic&&w>=900?.57:.5):this.course.atlas?.startsWith('gym-')?(w<700?.5:.28):.44);c.save();c.translate(x,floor);if(['Right lead','Left side'].includes(this.side))c.scale(-1,1);c.fillStyle='#071b2650';c.beginPath();c.ellipse(0,4,Math.min((right-left)*scale*.4,160),8,0,0,Math.PI*2);c.fill();c.shadowColor='#fff4ce';c.shadowBlur=5;const contactBottom=/jack|jump/i.test(name??this.move)?bottom:f.bottom;c.drawImage(f.c,-center*scale,-contactBottom*scale,f.c.width*scale,f.c.height*scale);c.restore();
 }
}
export async function drawPortrait(canvas,trainer){const im=await loadImage(['01','03','04','06'].includes(trainer)?`trainer-${trainer}`:trainer==='02'?'trainer02-march':'march');const rig=new Scene(canvas,()=>{});const fs=['01','03','04','06'].includes(trainer)?extractAtlas(im,trainer):rig.extract(im,trainer==='02'?'trainer02-march':'march');const f=fs[trainer==='04'?10:0],ctx=canvas.getContext('2d');canvas.width=240;canvas.height=260;ctx.clearRect(0,0,240,260);ctx.imageSmoothingEnabled=false;const scale=Math.min(215/(f.right-f.left),235/(f.bottom-f.top));ctx.drawImage(f.c,f.left,f.top,f.right-f.left,f.bottom-f.top,(240-(f.right-f.left)*scale)/2,250-(f.bottom-f.top)*scale,(f.right-f.left)*scale,(f.bottom-f.top)*scale);}
