import {rowCuts} from './atlas-grid.js';
// Atlas decoder. Atlas files are preserved; chroma keys are applied only at runtime.
export const sprites=new Map();
function decode(img,x,y,w,h,key){const c=document.createElement('canvas');c.width=w;c.height=h;const cx=c.getContext('2d');cx.drawImage(img,x,y,w,h,0,0,w,h);w=c.width;h=c.height;const im=cx.getImageData(0,0,w,h),d=im.data,seen=new Uint8Array(w*h),q=new Int32Array(w*h);let start=0,end=0;
const isKey=(r,g,b)=>key==='magenta'?r>150&&b>120&&g<100:(Math.max(r,g,b)-Math.min(r,g,b)<24&&r>85&&g>85&&b>85);
function push(n){if(n<0||n>=w*h||seen[n])return;seen[n]=1;const k=n*4;if(d[k+3]===0||isKey(d[k],d[k+1],d[k+2])){d[k+3]=0;q[end++]=n;}}
for(let i=0;i<w;i++){push(i);push((h-1)*w+i);}for(let j=0;j<h;j++){push(j*w);push(j*w+w-1);}while(start<end){const n=q[start++];if(n%w)push(n-1);if(n%w<w-1)push(n+1);push(n-w);push(n+w);}
// Pure magenta in enclosed spaces also belongs to the key, unlike neutral old art.
if(key==='magenta')for(let k=0;k<d.length;k+=4)if(isKey(d[k],d[k+1],d[k+2]))d[k+3]=0;
for(let k=0;k<d.length;k+=4){if(!d[k+3])continue;const l=d[k]*.2126+d[k+1]*.7152+d[k+2]*.0722;for(let c=0;c<3;c++)d[k+c]=Math.max(0,Math.min(255,(l+(d[k+c]-l)*1.18)*1.055));}cx.putImageData(im,0,0);let l=w,t=h,r=0,b=0;for(let j=0;j<h;j++)for(let i=0;i<w;i++)if(d[(j*w+i)*4+3]>20){l=Math.min(l,i);r=Math.max(r,i);t=Math.min(t,j);b=Math.max(b,j);}if(r<l)return c;const out=document.createElement('canvas');out.width=r-l+1;out.height=b-t+1;out.getContext('2d').drawImage(c,l,t,out.width,out.height,0,0,out.width,out.height);return out;}
export async function loadArt(){await Promise.all(['old','nature','interior','people','wilds','waters','homes','businesses','furnishings','frontier','crops','flowers','foliage'].map(async kind=>{const image=new Image();image.src=`./assets/${kind==='old'?'sprites':kind}.webp`;await image.decode();const rows=kind==='old'||kind==='people'?2:['wilds','waters','homes','businesses','furnishings','crops','foliage'].includes(kind)?3:4;
const probe=document.createElement('canvas');probe.width=image.width;probe.height=image.height;const pc=probe.getContext('2d');pc.drawImage(image,0,0);const alpha=pc.getImageData(0,0,image.width,image.height).data;
for(let col=0;col<4;col++){const x=Math.floor(col*image.width/4),right=Math.floor((col+1)*image.width/4),cuts=kind==='old'?[0,560,image.height]:rowCuts(alpha,image.width,image.height,x,right,rows);for(let row=0;row<rows;row++)sprites.set(`${kind}:${row*4+col}`,decode(image,x,cuts[row],right-x,cuts[row+1]-cuts[row],kind==='old'?'neutral':'magenta'));}}));}
export function paintSprite(ctx,key,x,y,width,{flip=false,alpha=1,sway=0}={}){const img=sprites.get(key);if(!img)return;const h=width*img.height/img.width;ctx.save();ctx.globalAlpha=alpha;ctx.translate(Math.round(x),Math.round(y));if(flip)ctx.scale(-1,1);if(sway)ctx.transform(1,0,sway,1,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(img,-width/2,-h+8,width,h);ctx.restore();}
const hitMasks=new WeakMap();
export function opaqueAt(key,nx,ny){const image=sprites.get(key);if(!image||nx<0||ny<0||nx>=1||ny>=1)return false;let data=hitMasks.get(image);if(!data){data=image.getContext('2d').getImageData(0,0,image.width,image.height).data;hitMasks.set(image,data);}return data[(Math.floor(ny*image.height)*image.width+Math.floor(nx*image.width))*4+3]>40;}

const shadows=new WeakMap();
export function paintShadow(ctx,key,x,y,width,{daylight=1,hour=12,flip=false}={}){const img=sprites.get(key);if(!img||daylight<.2)return;let mask=shadows.get(img);if(!mask){mask=document.createElement('canvas');mask.width=img.width;mask.height=img.height;const c=mask.getContext('2d');c.drawImage(img,0,0);c.globalCompositeOperation='source-in';c.fillStyle='#1a342c';c.fillRect(0,0,mask.width,mask.height);shadows.set(img,mask);}ctx.save();ctx.globalAlpha=.17*daylight;ctx.translate(x,y);const direction=Math.sin((hour-12)*Math.PI/16);ctx.transform(flip?-1:1,0,direction*.9,-.22-Math.abs(direction)*.15,0,0);ctx.drawImage(mask,-width/2,-width*img.height/img.width,width,width*img.height/img.width);ctx.restore();}
