import {CROPS} from './economy.js';
import {cropStatus} from './core.js';
import {plantAt,tendBeds} from './farming.js';
import {growthTime,nearby} from './farm-rules.js';
import {sprites} from './art.js';
export function mountBed({get,commit,toast}){const panel=document.getElementById('bed-care');let active=null;const el=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
function action(fn){try{const message=fn();commit();render(get().objects.find(o=>o.id===active));toast(message);}catch(e){toast(e.message);}}
function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
function render(o){active=o?.id;panel.hidden=!o||!['farmland','crop'].includes(o.type);panel.replaceChildren();if(panel.hidden)return;const s=get(),status=o.type==='farmland'?'empty':cropStatus(s,o),seed=CROPS.find(c=>c.id===o.crop?.kind);panel.append(el('strong',seed?`${seed.name} · your garden bed`:'What would you like to grow here?'));if(status==='empty'){panel.append(el('p','Choose a seed to plant this spot. Seeds are free.'));const grid=el('div','');grid.className='bed-seeds';for(const[cropIndex,c]of CROPS.entries()){const b=button(`${c.name} · ${c.grow} habits`,()=>action(()=>plantAt(s,o.id,c.id))),img=sprites.get(`crops:${cropIndex*2+1}`);if(img){const canvas=document.createElement('canvas');canvas.width=70;canvas.height=45;const cx=canvas.getContext('2d'),z=Math.min(66/img.width,42/img.height);cx.imageSmoothingEnabled=false;cx.drawImage(img,(70-img.width*z)/2,45-img.height*z,img.width*z,img.height*z);b.prepend(canvas);}grid.append(b);}panel.append(grid);}else{const remaining=Math.max(0,growthTime(s,o)-(s.progress-o.crop.at));panel.append(el('p',status==='thirsty'?'A little water will start this crop growing.':status==='ready'?'Ready to harvest. Your next crop is up to you.':`${remaining} completed habit${remaining===1?'':'s'} until harvest. This crop will never wither.`));if(status==='thirsty')panel.append(button('Water this bed',()=>action(()=>tendBeds(s,[o.id],'water'))));if(status==='ready')panel.append(button('Harvest this bed',()=>action(()=>tendBeds(s,[o.id],'harvest'))));if(!o.compost)panel.append(button('Enrich soil · 2 herbs + 1 mushroom',()=>action(()=>tendBeds(s,[o.id],'compost'))));}
panel.append(el('small',`${nearby(s,o,'sprinkler',2)?'Within sprinkler reach · ':''}${nearby(s,o,'greenhouse',4)?'Glasshouse growth boost · ':''}${o.compost?'Composted · ':''}Only this spot is affected.`));}
return{render};}
