const entries=[];
function add(id,name,group,unlock,w,h,sprite,size,extra={}){entries.push({id,name,group,unlock,w,h,sprite,size,space:'outside',...extra});}
add('witch','Herbalist cottage','Homes',0,3,3,'homes:1',190,{home:true,variants:['homes:1','old:0']});
add('dwarf','Craftsman cottage','Homes',8,3,3,'homes:6',190,{home:true,variants:['homes:6','old:1']});
add('cottage','Willow cottage','Homes',16,3,3,'homes:0',190,{home:true,variants:['homes:0','old:2']});
const trees=[['pine','Scots pine',0],['fir','Forest fir',0],['birch','Silver birch',3],['tree','Old oak',0],['willow','Weeping willow',6],['apple','Apple tree',8],['maple','Autumn maple',10],['bare','Winter tree',4]];
trees.forEach(([id,name,unlock],i)=>add(id,name,'Trees',unlock,2,2,`nature:${i}`,i===2?105:130,{activity:id==='apple'?'gather':null}));
[['fern','Woodland ferns',0],['grass','Meadow grasses',0],['hedge','Garden hedge',3],['berry','Berry bush',4],['shrub','White wildflowers',3],['lavender','Lavender',5],['sunflower','Sunflowers',6],['mushroom','Forest mushrooms',4]].forEach(([id,name,unlock],i)=>add(id,name,i<4?'Greenery':'Flowers',unlock,1,1,`nature:${i+8}`,i===6?65:55,{activity:['berry','fern','lavender','mushroom'].includes(id)?'gather':null}));
add('bench','Garden bench','Garden',5,2,1,'old:5',82,{activity:'rest'});
add('lantern','Firefly lantern','Garden',10,1,1,'old:6',65);
add('fence','Picket fence','Boundaries',0,2,1,'interior:10',95);
add('gate','Garden gate','Boundaries',2,2,1,'interior:11',90,{activity:'gate'});
add('door','Carved wooden door','Boundaries',0,1,1,'interior:12',65,{space:'both',activity:'gate'});
add('well','Stone well','Garden',4,2,2,'interior:13',100,{activity:'well'});
add('chicken','Hen','Animals',3,1,1,'interior:15',33,{activity:'eggs'});
add('crop','Vegetable bed','Farming',0,1,1,'interior:14',55,{activity:'crop'});
const floors=[['path','Old stone path','#a69e83'],['dirt','Earth trail','#a39565'],['farmland','Tilled farmland','#795844'],['gravel','Fine gravel','#969986'],['moss','Mossy ground','#677855'],['sand','Sandy bank','#c1b47f'],['water','Pond water','#547d83'],['brick','Brick walkway','#a47962'],['meadow','Meadow grass','#899752']];
floors.forEach(([id,name,color])=>add(id,name,'Land',0,1,1,null,64,{ground:true,color,activity:id==='water'?'fish':id==='farmland'?'till':null}));
[['bed','Cottage bed',0,2,3],['table','Round oak table',1,2,2],['chair','Carved chair',2,1,1],['bookcase','Library shelves',3,2,1],['fireplace','Stone hearth',4,2,1],['alchemy','Alchemy bench',5,2,1],['kitchen','Country kitchen',6,2,1],['chest','Keepsake chest',7,1,1],['rug','Woven rug',8,3,2],['pot','Indoor greenery',9,1,1]].forEach(([id,name,i,w,h])=>add(id,name,'Furniture',0,w,h,`interior:${i}`,id==='rug'?120:90,{space:'inside',ground:id==='rug',activity:id==='bed'?'rest':id==='alchemy'?'craft':null}));
add('oakfloor','Oak floor','Floors',0,1,1,null,64,{space:'inside',ground:true,color:'#ac845b'});
add('slatefloor','Slate floor','Floors',0,1,1,null,64,{space:'inside',ground:true,color:'#727d7b'});
add('tilefloor','Terracotta floor','Floors',0,1,1,null,64,{space:'inside',ground:true,color:'#ba8c70'});
add('herbpot','Enchanted herb pot','Crafted',0,1,1,'interior:9',65,{space:'both',recipe:true});
add('harvestbasket','Harvest basket','Crafted',0,1,1,'interior:14',55,{space:'both',recipe:true});
[['rabbit','Woodland rabbit',4],['fox','Forest fox',5],['sprite','Leaf sprite',6],['butterfly','Meadow butterfly',7]].forEach(([id,name,i])=>add(id,name,'Animals',4,1,1,`people:${i}`,i===7?22:35,{activity:'rest'}));

[['redwood','Towering redwood',0],['cedar','Mountain cedar',1],['spruce','Blue spruce',2],['blossom','Blossom tree',3],['snowpine','Snow-laden fir',4],['elder','Ancient willow',5]].forEach(([id,name,i])=>add(id,name,'Trees',8+i,2,2,`wilds:${i}`,i===0?180:145,{activity:'gather',resource:'wood'}));
[['stones','River stones',6,1,1,50],['boulder','Mossy boulder',7,2,2,105],['cliff','Layered cliff',8,3,2,155],['mountain','Mountain peak',9,4,4,230],['log','Fallen forest log',10,2,1,95],['stump','Hollow stump',11,1,1,70]].forEach(([id,name,i,w,h,size])=>add(id,name,'Wild places',4,w,h,`wilds:${i}`,size,{activity:'gather',resource:i<10?'stones':'wood'}));
[['waterfall','Woodland waterfall',0,3,3,185],['cascade','Cascading brook',1,2,2,110],['bridge','Arched footbridge',2,3,1,130],['crossing','Stepping stones',3,2,1,90],['reeds','Waterside reeds',4,1,1,60],['lilies','Water lilies',5,1,1,55],['dock','Fishing dock',6,2,2,110],['ruin','Ancient stone arch',7,2,2,130],['crystal','Moonlight crystals',8,1,1,75],['fairylamp','Fairy lantern',9,1,1,70],['fairyring','Mushroom circle',10,2,2,95],['shrine','Woodland shrine',11,2,2,120]].forEach(([id,name,i,w,h,size])=>add(id,name,i<7?'Water & banks':'Magic',6,w,h,`waters:${i}`,size,{waterCompatible:i<7,activity:i<2||i===6?'fish':i===10?'gather':i===11?'rest':null,resource:i===10?'mushrooms':undefined,glow:[8,9,11].includes(i),walkable:[2,3,6].includes(i)}));
[['grasshome','Meadow-roof cottage',0],['mosshome','Mosswood cottage',1],['treehouse','Canopy treehouse',2],['observatory','Wizard observatory',3],['greenhouse','Botanical greenhouse',4],['bakery','Woodland bakery',5],['forge','Dwarven forge',6],['teahouse','Forest tea pavilion',7],['library','Little forest library',8],['barn','Harvest barn',9]].forEach(([id,name,i])=>add(id,name,'Homes',12+i*2,3,3,`homes:${i}`,195,{home:true,glow:true}));
add('carriage','Wooden carriage','Garden',8,2,2,'homes:10',120);
add('pergola','Flower pergola','Garden',8,2,2,'homes:11',125);
add('stream','Flowing stream','Land',0,1,1,null,64,{ground:true,color:'#557f83',water:true,activity:'fish'});
add('snow','Snow-covered ground','Land',0,1,1,null,64,{ground:true,color:'#cddbd3'});
add('cobble','Mossy cobblestones','Land',0,1,1,null,64,{ground:true,color:'#858c77'});
add('leaflitter','Autumn forest floor','Land',0,1,1,null,64,{ground:true,color:'#9c8250'});
add('woodwalk','Wooden boardwalk','Land',0,1,1,null,64,{ground:true,color:'#9f835c',walkable:true});
[['inn','The Wayfarer Inn'],['tavern','Bramble & Barley Tavern'],['stable','Woodland stables'],['watermill','Brookside mill'],['tailor','Thread & Thistle'],['market','Harvest market'],['bathhouse','Moonwater baths'],['healer','Hearthroot infirmary'],['windmill','Hilltop windmill'],['apiary','Wildflower apiary']].forEach(([id,name],i)=>add(id,name,'Village trades',6+i*2,i===9?2:3,i===9?2:3,`businesses:${i}`,i===9?95:195,{home:i!==9,glow:i!==9,activity:i===9?'gather':null,resource:i===9?'honey':undefined}));
add('horse','Chestnut horse','Animals',10,1,1,'businesses:10',65,{activity:'rest'});
add('goat','Dairy goat','Animals',8,1,1,'businesses:11',47,{activity:'gather',resource:'milk'});
[['bar','Tavern counter',3,1],['feasttable','Supper table',2,2],['armchair','Velvet armchair',1,1],['fourposter','Canopied bed',2,3],['wardrobe','Carved wardrobe',2,1],['loom','Weaving loom',2,2],['barrel','Brewing barrel',1,1],['stove','Cooking stove',2,1],['manger','Hay manger',2,1],['bathtub','Wooden bath',2,1],['crate','Orchard crate',1,1],['partition','Arched partition',3,1]].forEach(([id,name,w,h],i)=>add(id,name,'Furnishings',0,w,h,`furnishings:${i}`,i===3?110:95,{space:'inside',activity:['bar','loom','stove','barrel'].includes(id)?'craft':null}));
[['cow','Dairy cow','milk'],['sheep','Woolly sheep','wool'],['pig','Truffle pig','mushrooms'],['duck','Pond duck','eggs']].forEach(([id,name,resource],i)=>add(id,name,'Farmyard',4+i,1,1,`frontier:${i}`,id==='cow'?60:43,{activity:'gather',resource}));
[['castlewall','Castle curtain wall',4,3,1,145],['castlegate','Castle gatehouse',5,3,2,165],['watchtower','Village watchtower',6,2,2,160],['barracks','Woodland barracks',7,3,3,190],['trebuchet','Timber trebuchet',11,2,2,120]].forEach(([id,name,i,w,h,size])=>add(id,name,'Fortifications',8,w,h,`frontier:${i}`,size,{home:id==='barracks',frontierOnly:id==='trebuchet',activity:id==='castlegate'?'gate':null}));
add('clocklibrary','Clockwork library','Homes',12,3,3,'frontier:12',205,{home:true,glow:true});
add('cave','Crystal grotto','Wild places',4,3,2,'frontier:13',160,{glow:true});
add('coop','Henhouse','Farmyard',4,2,2,'frontier:14',105);
add('sprinkler','Brass garden sprinkler','Farmyard',6,1,1,'frontier:15',58);
add('oldmill','Sleeping watermill','Restore & discover',0,3,3,'businesses:3',195,{activity:'restore'});
add('lostglasshouse','Forgotten glasshouse','Restore & discover',0,3,3,'homes:4',195,{activity:'restore'});
add('hiddengrotto','Veiled grotto','Restore & discover',0,3,2,'frontier:13',160,{activity:'restore'});
add('flowermeadow','Wildflower meadow','Land',0,1,1,null,64,{ground:true,color:'#78944d'});
add('steppath','Garden stepping path','Land',0,1,1,null,64,{ground:true,color:'#839651'});
[['daisies','White daisies'],['daffodils','Golden daffodils'],['bluebells','Woodland bluebells'],['poppies','Scarlet poppies'],['irises','Violet irises'],['roses','Coral roses'],['peonies','Blush peonies'],['marigolds','Amber marigolds'],['cosmos','White cosmos'],['delphiniums','Blue delphiniums'],['crocuses','Golden crocuses'],['hollyhocks','Cream hollyhocks'],['foxgloves','Peach foxgloves'],['snowdrops','Soft white snowdrops'],['orchids','Moon-green orchids'],['asters','Lilac asters']].forEach(([id,name],i)=>add(id,name,'Flowers',i<4?0:2+Math.floor(i/4),1,1,`flowers:${i}`,[9,11,12].includes(i)?76:57));
[['sagefern','Soft sage fern'],['limefern','Vivid lime fern'],['emeraldfern','Deep emerald fern'],['hosta','Blue-green hosta'],['goldgrass','Golden plume grass'],['bamboo','Jade bamboo'],['eucalyptus','Silver eucalyptus'],['laurel','Deep glossy laurel'],['clover','Bright clover'],['mossmound','Soft olive moss'],['ivytrellis','Emerald ivy trellis'],['variegated','Lime & cream shrub']].forEach(([id,name],i)=>add(id,name,'Greenery',i<4?0:i%4,1,1,`foliage:${i}`,[5,10].includes(i)?90:i===8||i===9?54:65));
[['maera','Maera · Hedge witch',3],['rowan','Rowan · Farmer',0],['torven','Torven · Dwarven maker',2],['elian','Elian · Wizard',1],['fenn','Fenn · Woodland ranger',0],['pippa','Pippa · Baker',3],['merrin','Merrin · Innkeeper',0],['ida','Ida · Weaver',3],['bram','Bram · Stable keeper',2]].forEach(([resident,name,sprite])=>add(`resident_${resident}`,name,'Residents',0,1,1,`people:${sprite}`,42,{resident}));
[['guard','Shieldguard sentry',8,42],['archer','Archer sentry',9,42],['cavalry','Mounted sentry',10,64],['siege','Trebuchet emplacement',11,80]].forEach(([resident,name,sprite,size])=>add(`resident_${resident}`,name,'Residents',0,1,1,`frontier:${sprite}`,size,{resident,guard:true,frontierOnly:true}));
export const CATALOG=entries;
export const itemById=id=>CATALOG.find(d=>d.id===id);
export const RECIPES=[{id:'herbpot',name:'Enchanted herb pot',cost:{herbs:3,berries:2}},{id:'harvestbasket',name:'Harvest basket',cost:{vegetables:3,eggs:2}}];
export const ROOM_THEMES={sage:'#899a78',cream:'#d3c8a6',plum:'#978392',blue:'#849caa'};
