import {growthTime,harvestBonus,nearby} from './farm-rules.js';
import {RESTORATIONS,restorePlace} from './restoration.js';
import {defaultFrontier,validateFrontier} from './frontier.js';
import {CROPS,defaultEconomy,validateEconomy,rewardHabitEconomy} from './economy.js';
import {ownedFrom} from './pricing.js';
import {REMOVED_TYPES} from './catalog.js';
import {CHARACTERS,STORIES,defaultSocial,defaultStory} from './lore.js';
import {DEFAULT_WORLD,TIME_MODES,WEATHER_MODES,SEASONS} from './environment.js';
export {CATALOG,itemById,RECIPES,ROOM_THEMES} from './catalog.js';
import {CATALOG,itemById,RECIPES,ROOM_THEMES} from './catalog.js';
export const WORLD_SIZE=128,MAX_OBJECTS=2400;
export const RESOURCE_KEYS=['herbs','berries','apples','mushrooms','vegetables','fish','eggs','wood','stones','wheat','pumpkins','strawberries','flax','honey','milk','wool'];
export function initialState(){const objects=[];let seq=0;const add=(type,x,y)=>objects.push({id:`seed-${++seq}`,type,x,y,rotation:0});add('witch',60,60);add('pine',58,60);add('dwarf',65,59);add('cottage',60,66);add('birch',67,66);add('tree',58,66);add('shrub',63,60);add('berry',63,62);add('bench',65,64);add('lantern',62,64);add('fern',59,64);add('mushroom',68,64);add('well',66,68);add('chicken',65,67);add('farmland',66,66);add('crop',66,66);add('water',68,60);add('water',68,61);add('water',69,60);add('water',69,61);for(let x=58;x<69;x++)add('path',x,63);for(let y=58;y<69;y++)if(y!==63)add('path',64,y);return {version:4,frontier:defaultFrontier(),economy:defaultEconomy(),progress:0,expansion:0,objects,events:[],rooms:{},inventory:Object.fromEntries(RESOURCE_KEYS.map(k=>[k,0])),crafted:[],activityLog:[],harvests:{},world:{...DEFAULT_WORLD},villageName:'Fernwood',owned:[...new Set(objects.map(o=>o.type))],favorites:[],social:defaultSocial(),story:defaultStory()};}
export function bounds(s){if(s.scope==='room')return {min:59-(s.level||0),max:69+(s.level||0)};const n=12+s.expansion*4;return {min:64-n/2,max:64+n/2};}
export function footprint(o){const d=itemById(o.type);return o.rotation%2?{w:d.h,h:d.w}:{w:d.w,h:d.h};}
export function isGround(o){return !!itemById(o.type)?.ground;}
export function canPlace(s,o,ignoreId){const d=itemById(o.type);if(!d||!Number.isInteger(o.x)||!Number.isInteger(o.y))return false;if(s.scope==='room'?d.space==='outside':d.space==='inside')return false;const f=footprint(o),b=bounds(s);if(o.x<b.min||o.y<b.min||o.x+f.w>b.max||o.y+f.h>b.max)return false;if(!ignoreId&&s.objects.length>= (s.scope==='room'?250:MAX_OBJECTS))return false;return !s.objects.some(p=>{if(p.id===ignoreId)return false;const q=footprint(p),overlap=o.x<p.x+q.w&&o.x+f.w>p.x&&o.y<p.y+q.h&&o.y+f.h>p.y;if(!overlap)return false;if(((d.id==='water'||d.water)&&!isGround(p)&&!itemById(p.type).waterCompatible)||(!d.ground&&!d.waterCompatible&&(p.type==='water'||itemById(p.type).water)))return true;if(isGround(o)!==isGround(p))return false;return true;});}
export function available(s,d,sandbox=false){return !d.frontierOnly&&(sandbox || s.story?.unlocked.includes(d.id) || (d.recipe ? s.crafted.includes(d.id) : s.progress>=d.unlock));}
export function ensureRoom(s,id){if(!s.objects.some(o=>o.id===id&&itemById(o.type)?.home))throw Error('Select a home first.');if(!s.rooms[id])s.rooms[id]={level:s.economy.upgrades[id]||0,wall:'sage',floor:'oakfloor',objects:[{id:`${id}-bed`,type:'bed',x:59,y:60,rotation:0},{id:`${id}-hearth`,type:'fireplace',x:64,y:59,rotation:0},{id:`${id}-table`,type:'table',x:64,y:64,rotation:0},{id:`${id}-rug`,type:'rug',x:63,y:64,rotation:0},{id:`${id}-shelf`,type:'bookcase',x:61,y:59,rotation:0},{id:`${id}-pot`,type:'pot',x:68,y:59,rotation:0}]};const room=s.rooms[id];if(!room.furnished){const type=s.objects.find(o=>o.id===id).type;const sets={inn:['fourposter','wardrobe','armchair'],tavern:['bar','barrel','feasttable'],stable:['manger','crate','chest'],tailor:['loom','wardrobe','crate'],bathhouse:['bathtub','pot','armchair'],bakery:['stove','crate','feasttable'],healer:['alchemy','bed','wardrobe'],watermill:['crate','barrel','chest'],library:['bookcase','bookcase','armchair'],clocklibrary:['bookcase','loom','alchemy'],barracks:['bed','wardrobe','crate']};if(sets[type]&&room.objects.every(o=>o.id.startsWith(id+'-'))){room.objects=sets[type].map((type,i)=>({id:`${id}-trade-${i}`,type,x:60+i*3,y:60,rotation:0}));room.objects.push({id:`${id}-hearth`,type:'fireplace',x:64,y:66,rotation:0});}room.furnished=true;}return room;}
export function validateState(raw){if(raw&&typeof raw==='object'){const drop=o=>!(o&&REMOVED_TYPES.has(o.type));if(Array.isArray(raw.objects)&&raw.objects.some(o=>!drop(o)))raw={...raw,objects:raw.objects.filter(drop)};if(raw.rooms&&typeof raw.rooms==='object')for(const[id,r]of Object.entries(raw.rooms))if(Array.isArray(r?.objects)&&r.objects.some(o=>!drop(o)))raw={...raw,rooms:{...raw.rooms,[id]:{...r,objects:r.objects.filter(drop)}}};}if(!raw||![1,2,3,4].includes(raw.version)||!Number.isSafeInteger(raw.progress)||raw.progress<0||raw.progress>1e9||!Number.isInteger(raw.expansion)||raw.expansion<0||raw.expansion>29||!Array.isArray(raw.objects)||raw.objects.length>MAX_OBJECTS||!Array.isArray(raw.events)||raw.events.length>10000)throw Error('Invalid village save.');const s={...initialState(),progress:raw.progress,expansion:raw.expansion,objects:[],events:[]};
function objects(list,target){if(!Array.isArray(list)||list.length>(target.scope==='room'?250:MAX_OBJECTS))throw Error('Too many objects.');const ids=new Set;for(const o of list){if(!o||typeof o.id!=='string'||!o.id.length||o.id.length>100||['__proto__','constructor','prototype'].includes(o.id)||ids.has(o.id)||!itemById(o.type)||![0,1].includes(o.rotation))throw Error('Invalid village object.');const clean={id:o.id,type:o.type,x:o.x,y:o.y,rotation:o.rotation};if(o.variant!==undefined){if(!Number.isInteger(o.variant)||o.variant<0||o.variant>=(itemById(o.type).variants?.length||1))throw Error('Invalid exterior style.');clean.variant=o.variant;}if(o.open!==undefined)clean.open=!!o.open;if(o.compost!==undefined){if(o.type!=='crop'||typeof o.compost!=='boolean')throw Error('Invalid soil.');clean.compost=o.compost;}if(o.restoration!==undefined){if(!RESTORATIONS.some(r=>r.id===o.type)||!Number.isInteger(o.restoration)||o.restoration<0||o.restoration>2)throw Error('Invalid restoration.');clean.restoration=o.restoration;}if(o.crop!==undefined){if(!['seed','watered'].includes(o.crop.stage)||!Number.isSafeInteger(o.crop.at)||o.crop.at<0||o.crop.at>raw.progress)throw Error('Invalid crop.');if(o.crop.kind!==undefined&&!CROPS.some(c=>c.id===o.crop.kind))throw Error('Invalid seed.');clean.crop={stage:o.crop.stage,at:o.crop.at,kind:o.crop.kind||'vegetables'};}if(!canPlace(target,clean))throw Error('Objects overlap or fall outside their room or meadow.');ids.add(o.id);target.objects.push(clean);}}
objects(raw.objects,s);for(const e of raw.events){if(typeof e!=='string'||!e.length||e.length>200)throw Error('Invalid reward history.');s.events.push(e);}if(new Set(s.events).size!==s.events.length)throw Error('Duplicate reward history.');if(raw.version===1)return s;
if(!raw.rooms||typeof raw.rooms!=='object'||Array.isArray(raw.rooms)||Object.keys(raw.rooms).length>300)throw Error('Invalid interiors.');for(const [id,r] of Object.entries(raw.rooms)){if(!s.objects.some(o=>o.id===id&&itemById(o.type).home)||!r||!Object.hasOwn(ROOM_THEMES,r.wall)||!['oakfloor','slatefloor','tilefloor'].includes(r.floor))throw Error('Invalid home interior.');const level=r.level??0;if(!Number.isInteger(level)||level<0||level>3)throw Error('Invalid room size.');const target={scope:'room',level,objects:[]};objects(r.objects,target);s.rooms[id]={level,furnished:true,wall:r.wall,floor:r.floor,objects:target.objects};}
for(const k of RESOURCE_KEYS){const n=raw.inventory?.[k]??(['wood','stones','wheat','pumpkins','strawberries','flax','honey','milk','wool'].includes(k)?0:undefined);if(!Number.isSafeInteger(n)||n<0||n>1e7)throw Error('Invalid inventory.');s.inventory[k]=n;}if(!Array.isArray(raw.crafted)||raw.crafted.some(id=>!RECIPES.some(r=>r.id===id))||new Set(raw.crafted).size!==raw.crafted.length)throw Error('Invalid recipes.');s.crafted=[...raw.crafted];if(!Array.isArray(raw.activityLog)||raw.activityLog.length>30||raw.activityLog.some(x=>typeof x!=='string'||x.length>200))throw Error('Invalid activity journal.');s.activityLog=[...raw.activityLog];if(!raw.harvests||typeof raw.harvests!=='object'||Array.isArray(raw.harvests)||Object.keys(raw.harvests).length>3000)throw Error('Invalid activity history.');for(const [k,v]of Object.entries(raw.harvests)){if(k.length>140||!Number.isSafeInteger(v)||v<0||v>raw.progress)throw Error('Invalid gathering history.');s.harvests[k]=v;}if(raw.world){const w=raw.world;if(!TIME_MODES.includes(w.time)||!WEATHER_MODES.includes(w.weather)||!SEASONS.includes(w.season)||typeof w.motion!=='boolean'||typeof w.sound!=='boolean')throw Error('Invalid world atmosphere.');s.world={time:w.time,weather:w.weather,season:w.season,motion:w.motion,sound:w.sound};}if(raw.version>=3){
if(typeof raw.villageName!=='string'||!raw.villageName.trim()||raw.villageName.length>40)throw Error('Invalid village name.');s.villageName=raw.villageName.trim();
if(!Array.isArray(raw.favorites)||raw.favorites.length>CATALOG.length||raw.favorites.some(id=>!itemById(id))||new Set(raw.favorites).size!==raw.favorites.length)throw Error('Invalid favorites.');s.favorites=[...raw.favorites];
const ids=CHARACTERS.map(c=>c.id),social=raw.social,story=raw.story;
if(!social||!Array.isArray(social.met)||social.met.some(id=>!ids.includes(id))||new Set(social.met).size!==social.met.length)throw Error('Invalid residents.');s.social.met=[...social.met];
for(const field of ['friendship','lastTalk','homes']){if(!social[field]||typeof social[field]!=='object'||Array.isArray(social[field])||Object.keys(social[field]).some(id=>!ids.includes(id)))throw Error('Invalid resident data.');for(const[id,value]of Object.entries(social[field])){if(field==='homes'){if(typeof value!=='string'||value.length>100)throw Error('Invalid home assignment.');if(s.objects.some(o=>o.id===value&&itemById(o.type).home))s.social.homes[id]=value;}else{if(!Number.isSafeInteger(value)||value<0||value>(field==='friendship'?20:s.progress))throw Error('Invalid friendship.');s.social[field][id]=value;}}}
if(!story||!Array.isArray(story.completed)||story.completed.some(id=>!STORIES.some(q=>q.id===id))||new Set(story.completed).size!==story.completed.length||!Array.isArray(story.unlocked)||story.unlocked.some(id=>!STORIES.some(q=>q.reward===id))||story.unlocked.length>STORIES.length)throw Error('Invalid stories.');s.story.completed=[...story.completed];s.story.unlocked=[...new Set(story.unlocked)];for(const key of ['harvests','fish','gathered']){const n=story.stats?.[key];if(!Number.isSafeInteger(n)||n<0||n>1e7)throw Error('Invalid activity totals.');s.story.stats[key]=n;}
}if(raw.owned!==undefined){if(!Array.isArray(raw.owned)||raw.owned.length>CATALOG.length||raw.owned.some(id=>typeof id!=='string'||!itemById(id))||new Set(raw.owned).size!==raw.owned.length)throw Error('Invalid purchases.');s.owned=[...raw.owned];}else s.owned=ownedFrom(s);s.frontier=validateFrontier(raw.frontier,s);s.economy=validateEconomy(raw.economy,s);for(const[id,r]of Object.entries(s.rooms)){if(r.level!==(s.economy.upgrades[id]||0))throw Error('Room size does not match its upgrade.');}return s;}
export function award(s,event){if(!event||typeof event.id!=='string'||!event.id.length||event.id.length>200)throw Error('A unique completion ID is required.');if(s.events.includes(event.id))return false;if(s.events.length>=10000)throw Error('Reward history is full. Connect server-side reward storage before continuing.');if(s.progress>=1e9)throw Error('Progress limit reached.');s.events.push(event.id);s.progress++;const when=event.at?new Date(event.at):(event.date?new Date(event.date+'T12:00:00'):new Date());rewardHabitEconomy(s,isNaN(when)?new Date():when);return true;}
export function expansionCost(s){return(s.expansion+1)*6;}
export function expand(s){if(s.expansion>=29)throw Error('Your village has reached its full size.');if(s.progress<expansionCost(s))throw Error(`Complete ${expansionCost(s)-s.progress} more habits to open the next meadow.`);s.expansion++;}
function log(s,text){s.activityLog.unshift(text);s.activityLog=s.activityLog.slice(0,30);return text;}
export function cropStatus(s,o){return !o.crop?'empty':o.crop.stage==='watered'?(s.progress-o.crop.at>=growthTime(s,o)?'ready':'growing'):'thirsty';}
export function interact(s,o){const d=itemById(o.type);if(!d?.activity)throw Error('Choose a garden, pond, animal, or activity object.');if(d.activity==='restore')return log(s,restorePlace(s,o.id));if(d.activity==='till'){const next={...o,type:'crop'};if(!canPlace(s,next,o.id))throw Error('Move the object above this soil before making a bed.');o.type='crop';return log(s,'A garden bed is ready. Choose your seed in Farm & work.');}if(d.activity==='gate'){o.open=!o.open;return o.open?'Opened.':'Closed.';}if(d.activity==='rest')return log(s,'A quiet moment to rest and enjoy the village.');if(d.activity==='well')return log(s,'Fresh water is ready for your garden. Select a vegetable bed to water it.');if(d.activity==='craft')return 'Open Activities to choose a recipe.';
if(d.activity==='crop'){const status=cropStatus(s,o),seed=CROPS.find(c=>c.id===(o.crop?.kind||s.economy.seed))||CROPS[0];if(status==='empty'){const watered=nearby(s,o,'sprinkler',2);o.crop={stage:watered?'watered':'seed',at:s.progress,kind:seed.id};return log(s,`${seed.name} planted. ${watered?'The nearby sprinkler watered it.':'Water the bed next.'}`);}if(status==='thirsty'){o.crop.stage='watered';o.crop.at=s.progress;return log(s,`${seed.name} watered. Ready after ${growthTime(s,o)} completed habits.`);}if(status==='growing')throw Error(`${Math.max(0,growthTime(s,o)-(s.progress-o.crop.at))} completed habits until harvest. No further watering needed.`);const bonus=harvestBonus(s,o);delete o.crop;delete o.compost;s.inventory[seed.id]+=seed.yield+bonus;s.economy.xp.Farmer++;s.story.stats.harvests++;return log(s,`Harvested ${seed.yield+bonus} ${seed.name.toLowerCase()}. +1 Farmer experience.`);}
// Gathering is limited by activity type per progress step, not by movable object IDs.
const resource=d.resource|| (d.activity==='fish'?'fish':d.activity==='eggs'?'eggs':o.type==='apple'?'apples':o.type==='berry'?'berries':o.type==='mushroom'?'mushrooms':'herbs');const key=`gather:${resource}`;if(s.harvests[key]===s.progress)throw Error('Let nature replenish. Complete another habit before gathering more.');s.harvests[key]=s.progress;s.inventory[resource]+=resource==='eggs'&&s.objects.some(p=>p.type==='coop')?2:1;const role=resource==='fish'?'Fisher':resource==='wood'?'Forester':resource==='stones'?'Miner':'Herbalist';s.economy.xp[role]++;s.story.stats.gathered++;if(resource==='fish')s.story.stats.fish++;return log(s,`Collected ${resource}. Your basket is growing.`);}
export function craft(s,id){const r=RECIPES.find(r=>r.id===id);if(!r)throw Error('Unknown recipe.');if(s.crafted.includes(id))throw Error('Already crafted. This decoration is now freely reusable.');if(Object.entries(r.cost).some(([k,n])=>s.inventory[k]<n))throw Error('Gather the ingredients shown in the recipe first.');for(const[k,n]of Object.entries(r.cost))s.inventory[k]-=n;s.crafted.push(id);return log(s,`${r.name} crafted and permanently unlocked.`);}

// Restore the edited layout/land while preserving rewards and atmosphere settings.
export function restoreEdit(current,snapshot){const prior=validateState(snapshot),restoredUpgrades=structuredClone(prior.economy.upgrades);for(const key of ['progress','events','inventory','crafted','harvests','activityLog','world','frontier','economy','social','story','villageName','favorites'])prior[key]=structuredClone(current[key]);prior.economy.upgrades=Object.fromEntries(Object.entries({...restoredUpgrades,...prior.economy.upgrades}).filter(([id])=>prior.objects.some(o=>o.id===id)));for(const[id,r]of Object.entries(prior.rooms))r.level=prior.economy.upgrades[id]||0;return prior;}
export function closeMeadow(s){if(s.expansion===0)throw Error('You are already at the starting meadow.');const next={...s,expansion:s.expansion-1},b=bounds(next);if(s.objects.some(o=>{const f=footprint(o);return o.x<b.min||o.y<b.min||o.x+f.w>b.max||o.y+f.h>b.max;}))throw Error('Move the pieces in the outer meadow inward before closing it.');s.expansion--;}

export function resetVillage(current,keepProgress=true){const next=initialState();next.world=structuredClone(current.world);if(keepProgress){for(const key of ['progress','events','inventory','crafted','harvests','activityLog','frontier','economy','social','story','villageName','favorites'])next[key]=structuredClone(current[key]);}next.economy.upgrades={};next.social.homes={};return next;}
