import {itemById} from './catalog.js';
export const CROPS=[
{id:'vegetables',name:'Turnips',grow:2,yield:2,price:3,color:'#e7d4a8'},
{id:'wheat',name:'Golden wheat',grow:3,yield:3,price:3,color:'#dbbc59'},
{id:'pumpkins',name:'Moon pumpkins',grow:4,yield:2,price:8,color:'#e9a050'},
{id:'strawberries',name:'Wild strawberries',grow:2,yield:2,price:5,color:'#e08086'},
{id:'herbs',name:'Silverleaf herbs',grow:1,yield:1,price:4,color:'#a5c2a0'},
{id:'flax',name:'Blue flax',grow:3,yield:3,price:4,color:'#9eabe1'}];
export const PROFESSIONS=['Farmer','Fisher','Herbalist','Forester','Miner','Cook','Weaver','Innkeeper'];
export const JOBS=[
{id:'supper',title:'Supper for the travelers',role:'Innkeeper',place:'inn',cost:{vegetables:2,eggs:1},coins:18,description:'Fill the inn pantry before the next wandering company arrives.'},
{id:'bread',title:'Bread for the village',role:'Cook',place:'bakery',cost:{wheat:3,eggs:1},coins:20,description:'Fresh loaves for windowsills and breakfast tables.'},
{id:'tonic',title:'A little forest medicine',role:'Herbalist',place:'healer',cost:{herbs:3,mushrooms:1},coins:20,description:'Help the healer prepare a soothing woodland tonic.'},
{id:'linen',title:'Linen for the guest rooms',role:'Weaver',place:'tailor',cost:{flax:3},coins:16,description:'Weave soft linen for the village’s newest visitors.'},
{id:'stable',title:'A warm and sturdy stable',role:'Forester',place:'stable',cost:{wood:2,wheat:2},coins:20,description:'Mend the stalls and prepare hay for the horses.'},
{id:'stew',title:'The tavern’s hearth stew',role:'Cook',place:'tavern',cost:{mushrooms:2,vegetables:2},coins:22,description:'Keep a warm pot ready beside the evening fire.'},
{id:'catch',title:'The miller’s lunch',role:'Fisher',place:'watermill',cost:{fish:2},coins:14,description:'Bring a fresh brook catch to the miller.'},
{id:'stone',title:'Mend the village well',role:'Miner',place:'well',cost:{stones:2},coins:12,description:'Replace the weathered stones around the well.'},
{id:'market',title:'Market morning',role:'Farmer',place:'market',cost:{strawberries:2,apples:1},coins:20,description:'Arrange fresh fruit at the harvest stall.'},
{id:'fleece',title:'Blankets for the inn',role:'Weaver',place:'tailor',cost:{wool:2},coins:16,description:'Soft wool becomes blankets for the winter guest rooms.'},
{id:'cream',title:'Cream for the bakery',role:'Farmer',place:'bakery',cost:{milk:2},coins:14,description:'Deliver fresh dairy for Pippa’s morning baking.'},
{id:'tea',title:'Tea beneath the leaves',role:'Herbalist',place:'teahouse',cost:{herbs:2,honey:1},coins:18,description:'A fragrant pot of tea and a spoonful of wildflower honey.'}
];
export function defaultEconomy(){return {habitDays:{},coins:0,seed:'vegetables',xp:Object.fromEntries(PROFESSIONS.map(k=>[k,0])),deliveries:{},upgrades:{},sold:0};}
export function validateEconomy(raw,s){if(raw===undefined)return defaultEconomy();const out=defaultEconomy();const number=(n,max=1e7)=>Number.isSafeInteger(n)&&n>=0&&n<=max;if(!raw||!number(raw.coins)||!number(raw.sold)||!CROPS.some(c=>c.id===raw.seed))throw Error('Invalid village economy.');if(raw.habitDays!==undefined){if(!raw.habitDays||typeof raw.habitDays!=='object'||Array.isArray(raw.habitDays)||Object.keys(raw.habitDays).length>8)throw Error('Invalid habit activity.');for(const[k,n]of Object.entries(raw.habitDays)){if(!/^\d{4}-\d{2}-\d{2}$/.test(k)||!Number.isSafeInteger(n)||n<0||n>1e7)throw Error('Invalid habit activity.');out.habitDays[k]=n;}}if(raw.pointsByDay!==undefined){if(!raw.pointsByDay||typeof raw.pointsByDay!=='object'||Array.isArray(raw.pointsByDay))throw Error('Invalid points record.');out.pointsByDay={};const days=Object.entries(raw.pointsByDay).filter(([k,n])=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&Number.isSafeInteger(n)&&n>=0&&n<=1e6).sort().slice(-400);for(const[k,n]of days)out.pointsByDay[k]=n;}out.coins=raw.coins;out.sold=raw.sold;out.seed=raw.seed;for(const role of PROFESSIONS){if(!number(raw.xp?.[role]))throw Error('Invalid profession.');out.xp[role]=raw.xp[role];}for(const field of ['deliveries','upgrades']){if(!raw[field]||typeof raw[field]!=='object'||Array.isArray(raw[field]))throw Error('Invalid work history.');for(const[id,n]of Object.entries(raw[field])){if(!number(n,field==='upgrades'?3:s.progress)||! (field==='upgrades'?s.objects.some(o=>o.id===id&&itemById(o.type).home):JOBS.some(j=>j.id===id)))throw Error('Invalid work record.');out[field][id]=n;}}return out;}
export function jobStatus(s,j){if(!s.objects.some(o=>o.type===j.place))return 'building';if(s.economy.deliveries[j.id]===s.progress)return 'rest';if(Object.entries(j.cost).some(([k,n])=>s.inventory[k]<n))return 'ingredients';return 'ready';}
export function deliver(s,id){const j=JOBS.find(j=>j.id===id);if(!j)throw Error('Unknown job.');const status=jobStatus(s,j);if(status!=='ready')throw Error(status==='building'?`Build ${itemById(j.place).name} first.`:status==='rest'?'Another completed habit brings a new order.':'Gather the requested ingredients first.');for(const[k,n]of Object.entries(j.cost))s.inventory[k]-=n;s.economy.coins+=j.coins;s.economy.xp[j.role]+=3;s.economy.deliveries[id]=s.progress;return `${j.title} completed. +${j.coins} copper · +3 ${j.role} experience.`;}
export function sell(s,resource){const crop=CROPS.find(c=>c.id===resource);const price=crop?.price||3;if(!Object.hasOwn(s.inventory,resource)||s.inventory[resource]<1)throw Error('Gather or harvest something first.');s.inventory[resource]--;s.economy.coins+=price;s.economy.sold++;return `Sold one ${crop?.name.toLowerCase()||resource} for ${price} copper.`;}
export function upgradeCost(s,id){const level=s.economy.upgrades[id]||0;return {coins:20*(level+1),wood:2*(level+1),stones:level+1};}
export function upgrade(s,id){const home=s.objects.find(o=>o.id===id&&itemById(o.type).home);if(!home)throw Error('Select a building to improve.');const level=s.economy.upgrades[id]||0;if(level>=3)throw Error('This building is fully expanded.');const cost=upgradeCost(s,id);if(s.economy.coins<cost.coins||s.inventory.wood<cost.wood||s.inventory.stones<cost.stones)throw Error('Gather the copper, wood and stone shown first.');s.economy.coins-=cost.coins;s.inventory.wood-=cost.wood;s.inventory.stones-=cost.stones;s.economy.upgrades[id]=level+1;if(s.rooms[id])s.rooms[id].level=level+1;return `${itemById(home.type).name} expanded to ${12+level*2} × ${12+level*2}. More room for your imagination.`;}

export function prosperity(s,now=new Date()){const today=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()),days=s.economy.habitDays||{};const count=Object.entries(days).filter(([day])=>{const age=(today-Date.parse(day+'T00:00:00Z'))/86400000;return age>=0&&age<7;}).reduce((sum,[,n])=>sum+n,0);return{count,bonus:Math.min(4,Math.floor(count/3)),label:count>=12?'Flourishing':count>=6?'Thriving':count>=3?'Growing':'Taking root'};}
export function rewardHabitEconomy(s,now=new Date()){const key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;s.economy.habitDays||={};s.economy.habitDays[key]=(s.economy.habitDays[key]||0)+1;const today=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate());s.economy.habitDays=Object.fromEntries(Object.entries(s.economy.habitDays).filter(([day])=>{const age=(today-Date.parse(day+'T00:00:00Z'))/86400000;return age>=0&&age<7;}));return 0;}
/* Points → copper. 10 points = 1 copper, credited on the delta so a day that keeps growing keeps paying and a corrected log never un-builds anything. */
export function creditPoints(s,day,points){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(day)))return 0;const pts=Math.max(0,Math.round(Number(points)||0));s.economy.pointsByDay||={};const prev=s.economy.pointsByDay[day]||0;if(pts<=prev)return 0;const add=Math.floor(pts/10)-Math.floor(prev/10);s.economy.pointsByDay[day]=pts;if(add>0)s.economy.coins+=add;return add;}
