export const UNITS=[{id:'guard',name:'Shieldguard',sprite:8,power:1,cost:12,place:'barracks'},{id:'archer',name:'Woodland archer',sprite:9,power:2,cost:18,place:'barracks'},{id:'cavalry',name:'Cavalry',sprite:10,power:3,cost:28,place:'stable'},{id:'siege',name:'Trebuchet crew',sprite:11,power:4,cost:40,place:'barracks'}];
export const CAVES=[{id:'mouth',name:'The lantern threshold',parent:null,habits:1,power:0,reward:{stones:3},text:'Root-bound steps descend into a hall of mica. Someone has left a dry place for a lantern.'},{id:'brook',name:'The underground brook',parent:'mouth',habits:2,power:1,reward:{fish:3,stones:2},text:'Silver fish flash beneath a bridge carved from a single fallen stone.'},{id:'roots',name:'The root cathedral',parent:'mouth',habits:2,power:1,reward:{herbs:3,mushrooms:3},text:'Ancient roots form vaulted arches. Pale mushrooms light the way without a flame.'},{id:'forge',name:'The forgotten forge',parent:'brook',habits:3,power:3,reward:{stones:6,wood:3},text:'Cold anvils stand beside a warm spring. There is enough good stone here for a new beginning.'},{id:'archive',name:'The clockwork archive',parent:'roots',habits:3,power:3,reward:{wood:5,herbs:4},text:'Brass moths sleep between shelves. A clock records the hours when someone is reading.'},{id:'heart',name:'The crystal heart',parent:'forge',also:'archive',habits:4,power:6,reward:{stones:10,wood:6},text:'Two passages meet beneath a ceiling of green stars. The village lanterns seem close, even here.'}];
export function defaultFrontier(){return {routine:'patrol',units:{guard:0,archer:0,cavalry:0,siege:0},discovered:[],mission:null,visits:0};}
export function validateFrontier(raw,s){if(raw===undefined)return defaultFrontier();if(!raw||!raw.units||!Array.isArray(raw.discovered)||new Set(raw.discovered).size!==raw.discovered.length||raw.discovered.some(id=>!CAVES.some(c=>c.id===id))||!Number.isSafeInteger(raw.visits)||raw.visits<0||raw.visits>1e7)throw Error('Invalid frontier save.');const f=defaultFrontier();if(raw.routine!==undefined){if(!['patrol','watch','rest'].includes(raw.routine))throw Error('Invalid garrison routine.');f.routine=raw.routine;}for(const u of UNITS){const n=raw.units[u.id];if(!Number.isInteger(n)||n<0||n>12)throw Error('Invalid garrison.');f.units[u.id]=n;}if(Object.values(f.units).reduce((a,b)=>a+b,0)>12)throw Error('Garrison capacity exceeded.');f.discovered=[...raw.discovered];f.visits=raw.visits;if(raw.mission!==null){const m=raw.mission;if(!m||!CAVES.some(c=>c.id===m.id)||!Number.isSafeInteger(m.at)||m.at<0||m.at>s.progress)throw Error('Invalid expedition.');f.mission={id:m.id,at:m.at};}return f;}
export const strength=s=>UNITS.reduce((n,u)=>n+s.frontier.units[u.id]*u.power,0);
export function recruit(s,id){const u=UNITS.find(u=>u.id===id);if(!u)throw Error('Unknown recruit.');if(!s.objects.some(o=>o.type===u.place))throw Error(`Build ${u.place} first.`);if(Object.values(s.frontier.units).reduce((a,b)=>a+b,0)>=12)throw Error('Your garrison is full: 12 companies.');if(s.economy.coins<u.cost||s.inventory.wheat<1)throw Error(`Recruitment needs ${u.cost} copper and 1 wheat.`);s.economy.coins-=u.cost;s.inventory.wheat--;s.frontier.units[id]++;return `${u.name} joins the village guard.`;}
export function accessible(s,c){return (!c.parent||s.frontier.discovered.includes(c.parent))&&(!c.also||s.frontier.discovered.includes(c.also));}
export function depart(s,id){const c=CAVES.find(c=>c.id===id);if(!c||!accessible(s,c))throw Error('Discover the connecting passages first.');if(s.frontier.mission)throw Error('An expedition is already underway.');if(!s.objects.some(o=>o.type==='cave'))throw Error('Place a cave entrance first.');if(strength(s)<c.power)throw Error(`This passage needs ${c.power} expedition strength.`);if(s.inventory.vegetables<1)throw Error('Pack 1 turnip from your garden for the expedition.');s.inventory.vegetables--;s.frontier.mission={id,at:s.progress};return `Expedition departed for ${c.name}. ${c.habits} completed habits until their return.`;}
export function returnExpedition(s){const m=s.frontier.mission,c=CAVES.find(c=>c.id===m?.id);if(!c)throw Error('No expedition is underway.');if(s.progress-m.at<c.habits)throw Error(`${c.habits-(s.progress-m.at)} more completed habits until the expedition returns.`);for(const[k,n]of Object.entries(c.reward))s.inventory[k]+=n;if(!s.frontier.discovered.includes(c.id))s.frontier.discovered.push(c.id);s.frontier.visits++;s.frontier.mission=null;return c.text+' Supplies safely delivered.';}

export function dismiss(s,id){const u=UNITS.find(u=>u.id===id);if(!u||reserveCount(s,id)<1)throw Error('Return a posted unit to its company before releasing it.');s.frontier.units[id]--;return `${u.name} released. A company slot is available.`;}

export const deployedCount=(s,id)=>s.objects.filter(o=>o.type===`resident_${id}`).length;
export const reserveCount=(s,id)=>Math.max(0,(s.frontier.units[id]||0)-deployedCount(s,id));
