/** Same-origin iframe adapter. Remove the frame with destroy() on route exit. */
export async function mountVillage(container,{baseUrl='/village/',load,onChange,onError=console.error,signal}={}){
 const url=new URL(baseUrl,location.href);if(url.origin!==location.origin)throw Error('Host the village assets on the same origin as SPYR.');if(signal?.aborted)throw Error('Village mount cancelled.');url.searchParams.set('embedded','1');
 const frame=document.createElement('iframe');frame.title='Your woodland village';frame.src=url.href;frame.style.cssText='display:block;width:100%;height:100%;border:0';let disposed=false,queue=Promise.resolve(),lastError=null,timer,abort;
 const loaded=new Promise((resolve,reject)=>{frame.onload=resolve;frame.onerror=()=>reject(Error('Village failed to load.'));timer=setTimeout(()=>reject(Error('Village loading timed out.')),20000);abort=()=>reject(Error('Village mount cancelled.'));signal?.addEventListener('abort',abort,{once:true});});container.append(frame);
 try{await loaded;clearTimeout(timer);signal?.removeEventListener('abort',abort);const api=frame.contentWindow.SPYRVillage;if(!api)throw Error('Village module did not initialize.');if(load){const saved=await load();if(signal?.aborted)throw Error('Village mount cancelled.');if(saved)api.loadState(saved);}
 function enqueue(snapshot){queue=queue.then(async()=>{api.setSaveStatus?.('saving');try{await onChange?.(snapshot);lastError=null;api.setSaveStatus?.('saved');}catch(error){lastError=error;api.setSaveStatus?.('error');try{onError(error);}catch{}}});return queue;}
 const listener=e=>enqueue(structuredClone(e.detail));const retry=()=>enqueue(api.getState());frame.contentWindow.addEventListener('spyr:village-change',listener);frame.contentWindow.addEventListener('spyr:village-retry',retry);
 return{recordHabitCompletion:event=>{if(disposed)throw Error('Village is unmounted.');return api.recordHabitCompletion(event);},getState:()=>api.getState(),loadState:s=>api.loadState(s),retry,async flush(){await queue;if(lastError)throw lastError;},destroy(){disposed=true;frame.contentWindow?.removeEventListener('spyr:village-change',listener);frame.contentWindow?.removeEventListener('spyr:village-retry',retry);frame.remove();}};
 }catch(error){clearTimeout(timer);signal?.removeEventListener('abort',abort);frame.remove();throw error;}
}
