import {itemById} from './catalog.js';
export const CHARACTERS=[
{id:'maera',name:'Maera Mosswick',role:'Herbalist & hedge witch',sprite:3,color:'#bea3bd',homes:['witch','mosshome','grasshome'],work:['fern','lavender','greenhouse','crop'],min:0,bio:'Maera can name a plant by its shadow. She came to Fernwood carrying three seed envelopes and a kettle that whistles before it rains.',greeting:'A village begins with someone deciding to stay. I think the ferns have already decided about you.',lines:['Leave a little wildness beside the paths. The useful things often grow where nobody planned.','The herbs are doing well. They like being noticed, but not fussed over.','I put a light in the window for anyone taking the long way home.']},
{id:'rowan',name:'Rowan Alder',role:'Gardener & orchard keeper',sprite:0,color:'#c3ba7c',homes:['cottage','barn','grasshome'],work:['crop','apple','chicken','well'],min:0,bio:'Rowan keeps spare seeds in every pocket and remembers every harvest by who shared it. His ambition is a village where nobody eats alone.',greeting:'I saved you the sunny patch. We can work out what belongs there together.',lines:['A watered garden is a promise, not a deadline. We can let it take its time.','The hens have opinions about where the flowers should go. None of them agree.','A table under a tree counts as a very good dining room.']},
{id:'torven',name:'Torven Flint',role:'Dwarven maker & stonemason',sprite:2,color:'#d1a581',homes:['dwarf','forge'],work:['forge','stones','boulder','ruin'],min:0,bio:'Torven repairs old things so carefully that they keep their stories. He insists that even a garden gate deserves a satisfying click.',greeting:'Good ground. Good timber. Room for a stubborn idea or two. We can make a home of this.',lines:['Stone remembers the river. That is why I round the edges by the footpath.','I made that bench wide enough for company. A practical decision, naturally.','A bridge should feel like an invitation, not an obstacle.']},
{id:'elian',name:'Elian Vesper',role:'Wizard & keeper of the night sky',sprite:1,color:'#9bbac9',homes:['observatory','library'],work:['observatory','library','crystal','shrine'],min:6,bio:'Elian charts constellations that appear only above places people love. He suspects Fernwood is about to acquire one of its own.',greeting:'There you are. The lights through these trees looked remarkably like a constellation.',lines:['The stars are patient company. There is no wrong hour to begin looking.','I found a pressed leaf inside the oldest atlas. Someone mapped a home before they mapped the world.','Every lit window adds a star to the village below.']},
{id:'fenn',name:'Fenn Briar',role:'Ranger & friend to woodland creatures',sprite:0,color:'#a6bb8d',homes:['treehouse','grasshome'],work:['treehouse','fairyring','elder','willow'],min:12,bio:'Fenn follows the small trails everyone else walks past. Foxes tolerate her company; the leaf sprites consider her an unusually tall relative.',greeting:'If you walk quietly, the woods will show you what they were doing before you arrived.',lines:['A fallen log is a whole neighborhood if you happen to be very small.','The fox likes the clearing. I would take that as a compliment.','Not every path needs paving. Some can stay secrets.']},
{id:'pippa',name:'Pippa Bramble',role:'Baker & village host',sprite:3,color:'#d2ad94',homes:['bakery','teahouse'],work:['bakery','teahouse','pergola','bench'],min:18,bio:'Pippa believes a warm loaf can solve most awkward introductions. She is collecting recipes with room in the margins for the names of friends.',greeting:'You must stay for tea. That was not a question, but I did make your favorite chair available.',lines:['There is always room for one more cup. We can fetch another stool.','The best recipe is the one somebody asks you to make again.','A village sounds different when its windows are open. Have you noticed?']},
{id:'merrin',name:'Merrin Wren',role:'Innkeeper & collector of travelers’ tales',sprite:0,color:'#d8b184',homes:['inn','tavern'],work:['inn','tavern','market','bench'],min:24,bio:'Merrin keeps a spare room made up for a guest whose name he has yet to learn. Every walking stick by the door comes with a story.',greeting:'A seat by the hearth or a room beneath the eaves? Both are yours when you need them.',lines:['I leave the kettle on when the fog comes down. Someone is always a little farther from home than they planned.','The tavern sign creaks in a different key every season. I have decided it counts as music.','A guest left a map with no destinations. Only the places where someone was kind.']},
{id:'ida',name:'Ida Thistledown',role:'Weaver & maker of small comforts',sprite:3,color:'#ada0c7',homes:['tailor'],work:['tailor','blossom','market','lavender'],min:30,bio:'Ida dyes her thread with flowers and fallen leaves. Her blankets always have one wandering stitch, so a dream can find its way out.',greeting:'Hold this thread a moment. Yes, there. You are part of the pattern already.',lines:['The woodland has more greens than I have names for. A pleasant problem.','I am making curtains for the inn. They should catch the morning, not keep it out.','The best things get mended. It means someone wanted to keep them.']},
{id:'bram',name:'Bram Copperfern',role:'Stable keeper & wandering farrier',sprite:2,color:'#b6bb83',homes:['stable','barn'],work:['stable','horse','goat','well','barn'],min:20,bio:'Bram knows every horse by its footsteps. He arrived with a chestnut mare and enough patience to teach the village goats some manners.',greeting:'Easy steps, warm hay, fresh water. A fine beginning for most days.',lines:['That chestnut mare likes apples better than compliments. Sensible creature.','The goat has inspected the new fence. Twice. We may need another latch.','There is a lovely trail beyond the tall cedars. We will keep it ready.']}

];
export function presentCharacters(s){return CHARACTERS.filter(c=>s.progress>=c.min||s.objects.some(o=>c.homes.includes(o.type)));}
export function characterHome(s,c){const assigned=s.social.homes[c.id];return s.objects.find(o=>o.id===assigned&&itemById(o.type)?.home)||s.objects.find(o=>c.homes.includes(o.type))||s.objects.find(o=>itemById(o.type)?.home);}
export function talk(s,id){const c=presentCharacters(s).find(c=>c.id===id);if(!c)throw Error('This resident has not arrived yet.');const first=!s.social.met.includes(id);if(first)s.social.met.push(id);const previous=s.social.lastTalk[id];if(previous!==s.progress){s.social.lastTalk[id]=s.progress;s.social.friendship[id]=Math.min(20,(s.social.friendship[id]||0)+1);}return first?c.greeting:c.lines[(s.progress+(s.social.friendship[id]||0))%c.lines.length];}
const has=(s,...types)=>s.objects.some(o=>types.includes(o.type));
export const STORIES=[
{id:'welcome',title:'A light among the ferns',resident:'maera',intro:'A lone lantern once marked the path into Fernwood. Maera would like it to become a welcome, rather than a warning to turn back.',tasks:[['Meet Maera',s=>s.social.met.includes('maera')],['Add flowers and a garden bench',s=>has(s,'bench')&&has(s,'shrub','lavender','sunflower')]],reward:'fairylamp',ending:'Maera hangs the lantern where its light catches the leaves. “There,” she says. “Now the path knows where it is going.” A little brightness settles between the branches.'},
{id:'harvest',title:'Something worth sharing',resident:'rowan',intro:'Rowan has set aside an empty basket. He says the first harvest belongs to everyone who helped the village feel like home.',tasks:[['Meet Rowan',s=>s.social.met.includes('rowan')],['Harvest your first vegetable bed',s=>s.story.stats.harvests>=1]],reward:'greenhouse',ending:'Rowan divides the harvest into small bundles and leaves one on every doorstep. By evening, somebody has returned a jar of jam, someone else a loaf, and Torven a very fine basket handle.'},
{id:'crossing',title:'The other bank',resident:'torven',intro:'Torven has been watching the water. “A stream is a lovely neighbor,” he says, “but it should not have the final word on where we can walk.”',tasks:[['Meet Torven',s=>s.social.met.includes('torven')],['Create a stream or pond with four water tiles',s=>s.objects.filter(o=>['stream','water'].includes(o.type)).length>=4],['Build a bridge or stepping-stone crossing',s=>has(s,'bridge','crossing')]],reward:'ruin',ending:'Torven tests the crossing, once alone and once carrying a tray of tea. It passes both inspections. Across the water, the ferns shelter the remains of an old stone arch.'},
{id:'library',title:'A room for rainy afternoons',resident:'maera',intro:'There is a book in Maera’s bag with a different handwriting on every page. She is looking for somewhere it can stay open.',tasks:[['Finish A light among the ferns',s=>s.story.completed.includes('welcome')],['Furnish a home with a bookcase and chair',s=>Object.values(s.rooms).some(r=>r.objects.some(o=>o.type==='bookcase')&&r.objects.some(o=>o.type==='chair'))]],reward:'library',ending:'The first page reads: “Things we know about this place.” Someone writes that the creek is deepest after rain. Someone else writes that the third stair creaks. There is plenty of paper left.'},
{id:'stars',title:'The village constellation',resident:'elian',intro:'Elian thinks the village has begun to resemble a constellation. He needs a few earthly points of light before he can finish his chart.',tasks:[['Meet Elian',s=>s.social.met.includes('elian')],['Place three lanterns or glowing decorations',s=>s.objects.filter(o=>['lantern','fairylamp','crystal','shrine'].includes(o.type)).length>=3]],reward:'observatory',ending:'Elian names the constellation The Open Door. He marks the brightest star where the village lantern hangs, then gives you the chart so you can decide where the next light belongs.'},
{id:'gathering',title:'A table beneath the leaves',resident:'pippa',intro:'Pippa is planning an evening with no special occasion. “Those are the ones worth practicing,” she says.',tasks:[['Welcome four residents',s=>s.social.met.length>=4],['Complete three village stories',s=>s.story.completed.length>=3],['Build a tea pavilion or flower pergola',s=>has(s,'teahouse','pergola')]],reward:'shrine',ending:'Chairs arrive from different homes. The cups do not match. Someone brings a fiddle, someone forgets the tune, and the forest keeps its own quiet time around you. Fernwood feels wonderfully ordinary. Fernwood feels yours.'}
];
export function storyStatus(s,story){return{done:s.story.completed.includes(story.id),tasks:story.tasks.map(([label,check])=>({label,done:!!check(s)})),ready:story.tasks.every(([,check])=>check(s))};}
export function completeStory(s,id){const story=STORIES.find(x=>x.id===id);if(!story)throw Error('Unknown story.');if(s.story.completed.includes(id))throw Error('This chapter is already in your journal.');if(!storyStatus(s,story).ready)throw Error('There is a little more to do before this chapter is ready.');s.story.completed.push(id);if(!s.story.unlocked.includes(story.reward))s.story.unlocked.push(story.reward);return story.ending;}
export const defaultSocial=()=>({met:[],friendship:{},lastTalk:{},homes:{}});
export const defaultStory=()=>({completed:[],unlocked:[],stats:{harvests:0,fish:0,gathered:0}});
