import {UNITS,reserveCount} from './frontier.js';
import {footprint,isGround,itemById,bounds} from './core.js';
import {CHARACTERS,characterHome} from './lore.js';
import {atmosphere} from './environment.js';
export const VILLAGER_SIZE=42;
const directions=[[1,0],[-1,0],[0,1],[0,-1]],key=p=>`${p.x},${p.y}`;
export function walkNetwork(state){const b=bounds(state),blocked=new Set();for(const o of state.objects){const d=itemById(o.type);if(d.walkable||d.resident||o.open)continue;if(!isGround(o)||o.type==='water'||d.water){const f=footprint(o);for(let y=0;y<f.h;y++)for(let x=0;x<f.w;x++)blocked.add(`${o.x+x},${o.y+y}`);}}for(const o of state.objects.filter(o=>itemById(o.type).walkable)){const f=footprint(o);for(let y=0;y<f.h;y++)for(let x=0;x<f.w;x++)blocked.delete(`${o.x+x},${o.y+y}`);}return{b,has:p=>p.x>=b.min&&p.y>=b.min&&p.x<b.max&&p.y<b.max&&!blocked.has(key(p))};}
export function findPath(net,start,end){if(!net.has(start)||!net.has(end))return[];const queue=[start],parent=new Map([[key(start),null]]);let head=0;while(head<queue.length&&head<4096){const p=queue[head++];if(key(p)===key(end)){const path=[];let k=key(end);while(parent.get(k)!==null){const[x,y]=k.split(',').map(Number);path.push({x,y});k=parent.get(k);}return path.reverse();}for(const[dx,dy]of directions){const q={x:p.x+dx,y:p.y+dy},k=key(q);if(net.has(q)&&!parent.has(k)){parent.set(k,key(p));queue.push(q);}}}return[];}
function approaches(net,o){if(!o)return[];const f=footprint(o),out=[];for(let x=-1;x<=f.w;x++)for(let y=-1;y<=f.h;y++){if(x>=0&&x<f.w&&y>=0&&y<f.h)continue;const p={x:o.x+x,y:o.y+y};if(net.has(p))out.push(p);}return out;}
export function createResidents(){let actors=new Map(),net,lastRefresh=-Infinity;
return function tick(state,time,delta,reduced){if(!net||time-lastRefresh>1100){net=walkNetwork(state);lastRefresh=time;}const sky=atmosphere(state.world),night=sky.hour<6||sky.hour>21,shelter=['rain','snow'].includes(sky.weather);const characters=state.objects.filter(o=>itemById(o.type).resident).map(o=>({...(CHARACTERS.find(c=>c.id===itemById(o.type).resident)||{name:itemById(o.type).name,work:[],homes:[]}),id:o.id,source:o,roleId:itemById(o.type).resident,guard:!!itemById(o.type).guard,art:itemById(o.type).sprite})),all=[...characters.map(c=>({...c,key:c.art})),...UNITS.flatMap(u=>Array.from({length:reserveCount(state,u.id)},(_,i)=>({id:`troop-${u.id}-${i}`,name:u.name,key:`frontier:${u.sprite}`,troop:true,work:['barracks','castlegate','watchtower','stable'],homes:['barracks','stable']}))),...['rabbit','fox','leaf sprite','butterfly'].map((id,i)=>({id,name:id,key:`people:${i+4}`,creature:true,work:['fairyring','fern','shrub','elder'],homes:[]}))];
const activeIds=new Set(all.map(c=>c.id));for(const id of actors.keys())if(!activeIds.has(id))actors.delete(id);
for(const c of all){let a=actors.get(c.id);if(a&&c.source&&a.anchor!==`${c.source.x},${c.source.y}`){actors.delete(c.id);a=null;}const home=c.creature?state.objects.find(o=>['tree','pine','willow'].includes(o.type)):characterHome(state,c);if(!a){const start=c.source&&net.has(c.source)?{x:c.source.x,y:c.source.y}:approaches(net,home)[0]||{x:64,y:63};if(!net.has(start))continue;a={id:c.id,anchor:c.source?`${c.source.x},${c.source.y}`:null,x:start.x,y:start.y,at:start,route:[],wait:0,steps:0,task:'Enjoying the village',key:c.key,hidden:false};actors.set(c.id,a);}a.key=c.key;a.homeId=home?.id;if(c.guard){a.at={x:c.source.x,y:c.source.y};a.x=c.source.x;a.y=c.source.y;a.hidden=false;a.walking=false;a.route=[];a.task='Standing guard';a.flip=c.source.rotation===1;continue;}
if(!net.has(a.at)){const next=approaches(net,home)[0];if(!next){a.hidden=true;continue;}a.at=next;a.x=next.x;a.y=next.y;a.route=[];}
if(reduced){a.hidden=false;continue;}
if(a.route.length){const next=a.route[0];if(!net.has(next)){a.route=[];continue;}const dx=next.x-a.x,dy=next.y-a.y,dist=Math.hypot(dx,dy),step=delta*(c.creature?.001:.00065);a.flip=dx-dy<0;a.walking=true;if(dist<=step){a.x=next.x;a.y=next.y;a.at=next;a.route.shift();if(!a.route.length){a.wait=c.troop&&state.frontier.routine==='watch'?18000:3500+(a.steps%4)*1200;a.task=a.destinationTask;a.hidden=a.sleeping&&!!home;}}else{a.x+=dx/dist*step;a.y+=dy/dist*step;}}
else{a.walking=false;a.wait-=delta;if(a.wait<=0){a.hidden=false;a.sleeping=false;let target=home,task='At home';if((night||shelter||(c.troop&&state.frontier.routine==='rest'))&&!c.creature&&home){task=night?'Resting at home':'Sheltering from the weather';a.sleeping=true;}else{const targets=state.objects.filter(o=>c.work.includes(o.type));const social=state.objects.filter(o=>['bench','teahouse','pergola','tavern','inn','market'].includes(o.type));const list=c.troop&&state.frontier.routine==='watch'?state.objects.filter(o=>['watchtower','castlegate','barracks'].includes(o.type)):sky.hour>17&&social.length?social:targets;if(list.length)target=list[a.steps%list.length];else{const origin=c.source||a.at;const wander=[];for(let dy=-5;dy<=5;dy++)for(let dx=-5;dx<=5;dx++){const spot={x:origin.x+dx,y:origin.y+dy};if(net.has(spot))wander.push(spot);}if(wander.length)target={...wander[(a.steps*17+c.id.length*3)%wander.length],type:'resident_rowan'};}task=c.creature?'Exploring the undergrowth':sky.hour>17?'Taking a little break':c.id==='maera'?'Tending herbs':c.id==='rowan'?'Checking the garden':c.id==='torven'?'Inspecting stonework':c.id==='elian'?'Studying the old magic':c.id==='pippa'?'Preparing something warm':c.id==='merrin'?'Welcoming travelers':c.id==='ida'?'Choosing thread and dyes':c.id==='bram'?'Checking the stables':'Watching the woodland';}a.steps++;const candidates=approaches(net,target).sort((p,q)=>Math.abs(p.x-a.x)+Math.abs(p.y-a.y)-Math.abs(q.x-a.x)-Math.abs(q.y-a.y));let path=[];for(const end of candidates.slice(0,5)){path=findPath(net,a.at,end);if(path.length||key(a.at)===key(end))break;}a.route=path;a.destinationTask=task;a.task=path.length?'On the way':task;if(!path.length){a.wait=5000;a.hidden=a.sleeping&&!!home;}}}}
return all.flatMap(c=>{const a=actors.get(c.id);if(!a)return[];return[{person:true,id:c.id,homeId:a.homeId,placed:!!c.source,name:c.name,task:a.task,hidden:a.hidden,x:a.x+.5,y:a.y+.5,depth:a.x+a.y+1,key:a.key,size:c.source?itemById(c.source.type).size:c.troop?(c.id.includes('cavalry')?64:c.id.includes('siege')?75:42):c.creature?(c.id==='butterfly'?14:23):VILLAGER_SIZE,flip:a.flip,bob:!reduced&&a.walking?Math.sin(time*.012)*1.2:0}];});};}
