import{blank,validate,shelves,log,CAPACITY}from'./model.js';
const $=id=>document.getElementById(id),embedded=new URLSearchParams(location.search).get('embedded')==='1'||window.parent!==window,KEY='spyr-reading:v1';let state=blank(),blocked=false,selection=null,archive=null,readingPage=0,confirmAction;
try{if(!embedded&&localStorage.getItem(KEY))state=validate(JSON.parse(localStorage.getItem(KEY)));}catch{blocked=true;$('notice').textContent='Stored library could not be read. It has not been overwritten. Export new changes before leaving.';}
function status(text){$('save-status').textContent=text;$('retry').hidden=!blocked;}
function save(session){if(!embedded&&!blocked)try{localStorage.setItem(KEY,JSON.stringify(state));}catch{blocked=true;}status(embedded?'Saving…':blocked?'Not saved · export a copy':'Saved on this device');window.dispatchEvent(new CustomEvent('spyr:reading-change',{detail:structuredClone(state)}));if(session)window.dispatchEvent(new CustomEvent('spyr:reading-session',{detail:structuredClone(session)}));render();}
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function book(b,i){const button=el('button',undefined,'book');let hash=0;for(const c of b.id)hash=(hash*31+c.charCodeAt(0))>>>0;button.style.setProperty('--book-color',['#526d61','#7d4e49','#526176','#8a6b40','#655578','#6f7347'][hash%6]);button.style.setProperty('--height',(158+hash%33)+'px');button.style.setProperty('--spine-width',(23+hash%12)+'px');button.style.setProperty('--lean',i===0?'-3deg':'0deg');button.setAttribute('aria-label',b.title+', '+(b.status==='completed'?'completed':b.page+' of '+b.total+' pages'));button.title=b.title+(b.author?' — '+b.author:'');button.append(el('span','✦','ornament'),el('span',b.title,'spine-title'),el('span',b.status==='completed'?'✓':Math.round(b.page/b.total*100)+'%','spine-progress'));button.onclick=()=>open(b);return button;}
function row(id,books,empty){const node=$(id);node.replaceChildren();if(!books.length){node.append(el('p',empty,'empty'));if(id==='reading'){const b=el('button','+ Add a book','empty-add');b.onclick=()=>open();node.append(b);}return;}books.forEach((b,i)=>node.append(book(b,i)));}
function render(){const groups=shelves(state);if(archive!==null&&archive>=groups.archived.length)archive=null;readingPage=Math.min(readingPage,Math.max(0,Math.ceil(groups.reading.length/CAPACITY)-1));row('reading',groups.reading.slice(readingPage*CAPACITY,(readingPage+1)*CAPACITY),'No current reads.');row('completed',archive===null?groups.recent:groups.archived[archive],'Finished books will appear here.');$('completed-label').textContent=archive===null?'Completed':'Shelf '+(archive+1);$('close-shelf').hidden=archive===null;$('reading-nav').replaceChildren();if(groups.reading.length>CAPACITY){for(const [text,delta]of[['←',-1],['→',1]]){const b=el('button',text);b.setAttribute('aria-label',delta<0?'Previous current reads':'Next current reads');b.disabled=delta<0?readingPage===0:(readingPage+1)*CAPACITY>=groups.reading.length;b.onclick=()=>{readingPage+=delta;render();};$('reading-nav').append(b);}}$('shelves').replaceChildren();$('collection-slots').replaceChildren();groups.archived.forEach((s,i)=>{const b=el('button',undefined,'shelf-token');b.append(el('span','▥','tally'),el('span','Shelf '+(i+1)),el('small','8 books'));b.setAttribute('aria-pressed',String(archive===i));b.onclick=()=>{archive=archive===i?null:i;render();};$('collection-slots').append(b);});if(!groups.archived.length)$('collection-slots').append(el('p','Full shelves collect here.','empty'));$('archive-count').textContent=groups.archived.length+' full shelves';$('archive-help').hidden=groups.archived.length>0;$('count').textContent=state.books.filter(b=>b.status==='completed').length+' finished';$('minutes').textContent=state.sessions.reduce((a,s)=>a+s.minutes,0)+' minutes read';}
function open(b){selection=b?.id||null;$('book-form').reset();$('form-error').textContent='';$('title').value=b?.title||'';$('author').value=b?.author||'';$('total').value=b?.total||'';$('page').value=b?.page||0;$('page').min=b?.page||0;$('page').max=b?.total||100000;$('book-status').value=b?.status||'reading';$('title').readOnly=!!b;$('author').readOnly=!!b;$('total').readOnly=!!b;const done=b?.status==='completed';$('page').readOnly=done;$('status-field').hidden=!!b;$('session-fields').hidden=!b||done;$('duration').required=!!b&&!done;$('dialog-title').textContent=b?b.title:'Add to your shelf';$('dialog-eyebrow').textContent=done?'COMPLETED':b?'LOG READING':'NEW BOOK';$('submit').hidden=done;$('submit').textContent=b?'Save reading session':'Add book';$('delete').hidden=!b;$('progress').textContent=b?'Current progress: '+b.page+' / '+b.total+' pages. Logging the final page completes this book.':'';$('history').replaceChildren();if(b){const logs=state.sessions.filter(s=>s.bookId===b.id).reverse();if(logs.length){$('history').append(el('h3','Reading history'));for(const s of logs)$('history').append(el('p',new Date(s.at).toLocaleDateString()+' · '+s.minutes+' min · pages '+s.from+'–'+s.to));}else $('history').append(el('p','No reading sessions logged.'));}$('book-dialog').showModal();}
$('add').onclick=()=>open();$('close').onclick=()=>$('book-dialog').close();$('close-shelf').onclick=()=>{archive=null;render();};$('total').oninput=()=>{$('page').max=$('total').value;};
$('book-form').onsubmit=e=>{e.preventDefault();try{let session;if(selection){state=log(state,selection,{page:Number($('page').value),minutes:Number($('duration').value)});session=state.sessions.at(-1);}else{const total=Number($('total').value),done=$('book-status').value==='completed',now=new Date().toISOString();state=validate({...state,books:[...state.books,{id:crypto.randomUUID(),title:$('title').value.trim(),author:$('author').value.trim(),total,page:done?total:Number($('page').value),status:done?'completed':'reading',createdAt:now,...(done?{completedAt:now}:{})}]});}save(session);$('book-dialog').close();}catch(e){$('form-error').textContent=e.message;}};
function confirm(title,body,action){$('confirm-title').textContent=title;$('confirm-body').textContent=body;confirmAction=action;$('confirm').showModal();}$('cancel').onclick=()=>$('confirm').close();$('proceed').onclick=()=>{$('confirm').close();confirmAction?.();confirmAction=null;};$('delete').onclick=()=>confirm('Remove this book?','The book and its reading history will be removed from this library.',()=>{state={...state,books:state.books.filter(b=>b.id!==selection),sessions:state.sessions.filter(s=>s.bookId!==selection)};save();$('book-dialog').close();});
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='spyr-reading.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>10000000)throw Error('Choose a backup under 10 MB.');const incoming=validate(JSON.parse(await f.text()));confirm('Replace this library?',incoming.books.length+' books will replace this library. Export first to keep a copy.',()=>{state=incoming;archive=null;save();});}catch(e){$('notice').textContent=e.message;}finally{$('file').value='';}};
$('retry').onclick=()=>{if(embedded){window.dispatchEvent(new CustomEvent('spyr:reading-retry'));return;}try{const raw=localStorage.getItem(KEY);if(raw)validate(JSON.parse(raw));blocked=false;save();}catch{$('notice').textContent='Existing storage is still unreadable. Export a copy first.';}};
window.SPYRReading={getState:()=>structuredClone(state),loadState(raw){state=validate(raw);archive=null;render();},flush(){},setSaveStatus(value){blocked=value==='error';status(value==='error'?'Save failed · retry':value==='saving'?'Saving…':'Saved');}};if(embedded){$('export').hidden=true;$('import').hidden=true;status('');}else status(blocked?'Not saved · export a copy':'Saved on this device');render();

if(embedded){document.body.classList.add('embedded');for(const id of ['export','import'])$(id).hidden=true;$('host-exit').hidden=false;$('host-exit').onclick=()=>{try{window.parent.postMessage({type:'spyr:shelf-exit'},location.origin);}catch{}};}
